import { TarotCard } from './cards-data';

export const lenormandCards: TarotCard[] = [
  {
    id: 1,
    slug: 'rider',
    nameEn: 'Rider',
    nameVi: 'Kỵ Sĩ',
    arcana: 'major',
    number: '1',
    keywordsVi: ['tin tức đến nhanh', 'chuyển động', 'khách ghé thăm', 'sự xuất hiện đột ngột'],
    meaningUpright: 'Kỵ Sĩ mang tin tức đến nhanh chóng từ bên ngoài. Đây là sự chuyển động năng lượng tích cực, báo hiệu một cuộc gặp gỡ, tin nhắn hoặc thay đổi đời sống thực tế sắp sửa diễn ra.',
    meaningReversed: 'Trạng thái ngược chỉ tin tức bị chậm trễ, sự trì hoãn ngoài ý muốn hoặc một người khách mang theo tin buồn hay sự phiền phức.',
    imagePath: '/Lenormand/H09.png' // 9 of Hearts
  },
  {
    id: 2,
    slug: 'clover',
    nameEn: 'Clover',
    nameVi: 'Cỏ Ba Lá',
    arcana: 'major',
    number: '2',
    keywordsVi: ['may mắn ngắn hạn', 'cơ hội bất ngờ', 'niềm vui nhỏ', 'hy vọng'],
    meaningUpright: 'Cỏ Ba Lá đại diện cho may mắn bất ngờ nhưng mang tính thời điểm ngắn hạn. Đây là thời cơ tốt lành, hãy nắm bắt ngay để gặt hái thành công nhỏ.',
    meaningReversed: 'Trạng thái ngược cảnh báo vận may bị tuột mất do do dự, sự thất vọng nhẹ hoặc khó khăn tạm thời kéo dài hơn dự kiến.',
    imagePath: '/Lenormand/D06.png' // 6 of Diamonds
  },
  {
    id: 3,
    slug: 'ship',
    nameEn: 'Ship',
    nameVi: 'Con Tàu',
    arcana: 'major',
    number: '3',
    keywordsVi: ['hành trình xa', 'giao thương rộng mở', 'khám phá phương trời mới', 'sự dịch chuyển'],
    meaningUpright: 'Con Tàu căng buồm đại diện cho những chuyến đi xa, hành trình du lịch hoặc cơ hội giao thương mở rộng ra ngoài biên giới quen thuộc.',
    meaningReversed: 'Trạng thái ngược chỉ chuyến đi bị hủy bỏ, sự trì trệ trong giao thương hoặc cảm giác lạc lối mất phương hướng.',
    imagePath: '/Lenormand/S10.png' // 10 of Spades
  },
  {
    id: 4,
    slug: 'house',
    nameEn: 'House',
    nameVi: 'Ngôi Nhà',
    arcana: 'major',
    number: '4',
    keywordsVi: ['gia đình yên ấm', 'sự an toàn vững bền', 'nơi nương náu', 'nền tảng cuộc sống'],
    meaningUpright: 'Ngôi Nhà tượng trưng cho tổ ấm gia đình, sự an toàn vững chắc về mặt đời sống và tinh thần. Nơi nương tựa bình yên của bạn.',
    meaningReversed: 'Trạng thái ngược chỉ sự bất hòa trong gia đình, rắc rối liên quan đến bất động sản hoặc cảm giác không an toàn ở nhà.',
    imagePath: '/Lenormand/H13.png' // King of Hearts
  },
  {
    id: 5,
    slug: 'tree',
    nameEn: 'Tree',
    nameVi: 'Cây Cối',
    arcana: 'major',
    number: '5',
    keywordsVi: ['sức khỏe dẻo dai', 'sự sinh trưởng lâu dài', 'cội nguồn tổ tiên', 'sức bền'],
    meaningUpright: 'Cây Cối cắm rễ sâu biểu thị sức khỏe thể chất dẻo dai, sự sinh trưởng phát triển chậm rãi lâu dài và kết nối với nguồn cội gia đình.',
    meaningReversed: 'Trạng thái ngược cảnh báo sức khỏe suy giảm, tình trạng trì trệ thiếu sinh khí hoặc các vấn đề sức khỏe di truyền.',
    imagePath: '/Lenormand/H07.png' // 7 of Hearts
  },
  {
    id: 6,
    slug: 'clouds',
    nameEn: 'Clouds',
    nameVi: 'Mây Mù',
    arcana: 'major',
    number: '6',
    keywordsVi: ['sự mơ hồ', 'hoang mang bối rối', 'rắc rối tạm thời', 'thời tiết u ám'],
    meaningUpright: 'Mây Mù che lấp ánh dương biểu thị giai đoạn mơ hồ hoang mang, thiếu thông tin sáng tỏ dẫn đến bối rối trong việc đưa ra quyết định.',
    meaningReversed: 'Trạng thái ngược chỉ mây mù bắt đầu tan biến, sự thật hiển lộ và khó khăn được giải quyết dứt điểm.',
    imagePath: '/Lenormand/C13.png' // King of Clubs
  },
  {
    id: 7,
    slug: 'snake',
    nameEn: 'Snake',
    nameVi: 'Con Rắn',
    arcana: 'major',
    number: '7',
    keywordsVi: ['sự phản bội', 'lừa dối xảo quyệt', 'ghen tị ghen ghét', 'sự cám dỗ'],
    meaningUpright: 'Con Rắn cảnh báo sự phản bội lén lút, thói xảo quyệt lừa lọc từ người xung quanh hoặc sự ghen tị đố kỵ độc hại cần đề phòng cảnh giác.',
    meaningReversed: 'Trạng thái ngược chỉ ra âm mưu phản bội bị bại lộ kịp thời, rắc rối qua đi hoặc sự thức tỉnh thoát khỏi cám dỗ.',
    imagePath: '/Lenormand/C12.png' // Queen of Clubs
  },
  {
    id: 8,
    slug: 'coffin',
    nameEn: 'Coffin',
    nameVi: 'Quan Tài',
    arcana: 'major',
    number: '8',
    keywordsVi: ['sự kết thúc triệt để', 'mất mát lớn', 'buông bỏ bắt buộc', 'bệnh tật nặng'],
    meaningUpright: 'Quan Tài báo hiệu sự kết thúc triệt để của một giai đoạn, mối quan hệ hay hoàn cảnh cũ để nhường chỗ cho sự đổi thay bắt buộc.',
    meaningReversed: 'Trạng thái ngược chỉ sự trì hoãn hồi phục sau mất mát, cố bám víu thứ đã kết thúc hoặc bắt đầu quá trình chữa lành chậm chạp.',
    imagePath: '/Lenormand/D09.png' // 9 of Diamonds
  },
  {
    id: 9,
    slug: 'bouquet',
    nameEn: 'Bouquet',
    nameVi: 'Bó Hoa',
    arcana: 'major',
    number: '9',
    keywordsVi: ['món quà bất ngờ', 'niềm vui hạnh phúc', 'sự công nhận', 'ngày lễ chúc mừng'],
    meaningUpright: 'Bó Hoa tươi thắm mang đến món quà bất ngờ tốt đẹp, niềm vui hân hoan, sự công nhận xứng đáng và vẻ đẹp nghệ thuật tỏa sáng.',
    meaningReversed: 'Trạng thái ngược chỉ sự kiêu căng ngạo mạn làm mất lòng tin, món quà giả tạo hoặc sự công nhận bị trì hoãn nhẹ.',
    imagePath: '/Lenormand/S12.png' // Queen of Spades
  },
  {
    id: 10,
    slug: 'scythe',
    nameEn: 'Scythe',
    nameVi: 'Lưỡi Hái',
    arcana: 'major',
    number: '10',
    keywordsVi: ['cắt đứt đột ngột', 'tai nạn nguy hiểm', 'quyết định dứt khoát', 'thu hoạch'],
    meaningUpright: 'Lưỡi Hái sắc bén mang năng lượng cắt đứt đột ngột, kết thúc nhanh chóng một việc mà không có cảnh báo trước. Cần hành xử dứt khoát.',
    meaningReversed: 'Trạng thái ngược cảnh báo nguy hiểm tiềm ẩn kéo dài, quyết định nửa vời gây rắc rối hoặc tai nạn được ngăn chặn kịp thời.',
    imagePath: '/Lenormand/D11.png' // Jack of Diamonds
  },
  {
    id: 11,
    slug: 'whip',
    nameEn: 'Whip',
    nameVi: 'Roi Da',
    arcana: 'major',
    number: '11',
    keywordsVi: ['xung đột cãi vã', 'lặp đi lặp lại', 'áp lực trừng phạt', 'hoạt động thể chất'],
    meaningUpright: 'Roi Da biểu thị xung đột cãi vã gay gắt, tranh chấp lặp đi lặp lại hoặc áp lực công việc/cuộc sống dồn dập gây căng thẳng thần kinh.',
    meaningReversed: 'Trạng thái ngược chỉ sự hòa giải mâu thuẫn bắt đầu, chấm dứt vòng lặp tranh cãi tiêu cực mệt mỏi.',
    imagePath: '/Lenormand/C11.png' // Jack of Clubs
  },
  {
    id: 12,
    slug: 'birds',
    nameEn: 'Birds',
    nameVi: 'Chim Chóc',
    arcana: 'major',
    number: '12',
    keywordsVi: ['trò chuyện giao tiếp', 'tin đồn xôn xao', 'cặp đôi chia sẻ', 'lo âu nhẹ'],
    meaningUpright: 'Chim Chóc líu lo mang đến các cuộc trò chuyện, thảo luận hội họp nhóm, tin đồn xôn xao dư luận xã hội hoặc sự giao lưu chia sẻ thân mật.',
    meaningReversed: 'Trạng thái ngược chỉ sự hiểu lầm giao tiếp, thông tin đồn thổi độc hại hoặc sự im lặng ghẻ lạnh giữa đôi bên.',
    imagePath: '/Lenormand/D07.png' // 7 of Diamonds
  },
  {
    id: 13,
    slug: 'child',
    nameEn: 'Child',
    nameVi: 'Đứa Trẻ',
    arcana: 'major',
    number: '13',
    keywordsVi: ['khởi đầu mới', 'ngây thơ thuần khiết', 'con cái nhỏ bé', 'thiếu kinh nghiệm'],
    meaningUpright: 'Đứa Trẻ tượng trưng cho một khởi đầu mới mẻ đầy hứa hẹn, lòng ngây thơ trong sáng rộng mở học hỏi, hoặc việc chăm sóc con cái.',
    meaningReversed: 'Trạng thái ngược chỉ sự vô trách nhiệm trẻ con, sự ngây thơ khờ khạo bị lợi dụng hoặc rắc rối nhỏ phát sinh do thiếu kinh nghiệm.',
    imagePath: '/Lenormand/S11.png' // Jack of Spades
  },
  {
    id: 14,
    slug: 'fox',
    nameEn: 'Fox',
    nameVi: 'Con Cáo',
    arcana: 'major',
    number: '14',
    keywordsVi: ['công việc mưu sinh', 'khôn khéo cảnh giác', 'lừa dối ẩn giấu', 'sinh tồn'],
    meaningUpright: 'Con Cáo đại diện cho công việc hàng ngày, sự mưu sinh khôn khéo và tinh thần cảnh giác cao độ trước các bẫy rập xung quanh.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự không trung thực trong công sở, âm mưu lừa dối tinh vi bị phanh phui hoặc sự khôn lỏi phản tác dụng.',
    imagePath: '/Lenormand/C09.png' // 9 of Clubs
  },
  {
    id: 15,
    slug: 'bear',
    nameEn: 'Bear',
    nameVi: 'Con Gấu',
    arcana: 'major',
    number: '15',
    keywordsVi: ['sức mạnh bảo vệ', 'tài chính dồi dào', 'người mẹ che chở', 'thế lực uy quyền'],
    meaningUpright: 'Con Gấu đại diện cho sức mạnh cơ bắp và tinh thần, khả năng bảo vệ vững vàng gia sản, sự thịnh vượng tài chính dồi dào và tình mẫu tử bao la.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự lạm dụng uy quyền chèn ép kẻ yếu, thói ích kỷ thống trị hoặc rủi ro thất thoát tiền của.',
    imagePath: '/Lenormand/C10.png' // 10 of Clubs
  },
  {
    id: 16,
    slug: 'stars',
    nameEn: 'Stars',
    nameVi: 'Ngôi Sao',
    arcana: 'major',
    number: '16',
    keywordsVi: ['hy vọng định hướng', 'ước mơ thành hiện thực', 'tầm nhìn rộng lớn', 'sự khai sáng'],
    meaningUpright: 'Ngôi Sao thắp sáng bầu trời mang đến niềm hy vọng phục hồi, ước mơ hoài bão có cơ hội thành hiện thực dưới sự định hướng đúng đắn.',
    meaningReversed: 'Trạng thái ngược chỉ sự thiếu định hướng rõ ràng, hoài nghi ước mơ của bản thân hoặc hoãn lại các dự án nghệ thuật.',
    imagePath: '/Lenormand/H06.png' // 6 of Hearts
  },
  {
    id: 17,
    slug: 'stork',
    nameEn: 'Stork',
    nameVi: 'Chim Cò',
    arcana: 'major',
    number: '17',
    keywordsVi: ['sự thay đổi chuyển biến', 'di chuyển sinh đẻ', 'chu kỳ tiến hóa', 'cải tiến tốt đẹp'],
    meaningUpright: 'Chim Cò biểu thị những thay đổi tích cực lớn lao, sự di cư chuyển chỗ ở mới, cơ hội mang thai sinh nở tốt lành hoặc cải tiến đời sống.',
    meaningReversed: 'Trạng thái ngược chỉ sự kháng cự lại sự thay đổi bắt buộc, trì hoãn chuyển đổi hoặc khó khăn tạm thời trong thích nghi.',
    imagePath: '/Lenormand/H12.png' // Queen of Hearts
  },
  {
    id: 18,
    slug: 'dog',
    nameEn: 'Dog',
    nameVi: 'Chú Chó',
    arcana: 'major',
    number: '18',
    keywordsVi: ['trung thành tin cậy', 'tình bạn tri kỷ', 'người hỗ trợ âm thầm', 'đồng hành'],
    meaningUpright: 'Chú Chó là biểu tượng của lòng trung thành son sắt, tình bạn tri kỷ đáng tin cậy bên cạnh hỗ trợ đồng hành âm thầm vượt khó khăn.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự phản bội từ người tin cậy, mối quan hệ bạn bè rạn nứt hoặc lòng tin đặt sai chỗ.',
    imagePath: '/Lenormand/H10.png' // 10 of Hearts
  },
  {
    id: 19,
    slug: 'tower',
    nameEn: 'Tower',
    nameVi: 'Tòa Tháp',
    arcana: 'major',
    number: '19',
    keywordsVi: ['cơ quan luật pháp', 'độc lập tự chủ', 'cô lập giam cầm', 'tầm nhìn vĩ mô'],
    meaningUpright: 'Tòa Tháp đại diện cho các tổ chức công quyền nhà nước, sự tự chủ độc lập làm chủ cuộc đời hoặc sự cô lập tĩnh lặng nghiên cứu chiều sâu.',
    meaningReversed: 'Trạng thái ngược chỉ cảm giác bị giam cầm ngột ngạt trong cấu trúc hành chính, sự cô độc cực đoan tự kỷ ám thị lâu dài.',
    imagePath: '/Lenormand/S06.png' // 6 of Spades
  },
  {
    id: 20,
    slug: 'garden',
    nameEn: 'Garden',
    nameVi: 'Khu Vườn',
    arcana: 'major',
    number: '20',
    keywordsVi: ['cộng đồng xã hội', 'sự kiện đông đúc', 'mối quan hệ công chúng', 'vui chơi giải trí'],
    meaningUpright: 'Khu Vườn biểu thị các hoạt động cộng đồng xã hội nhộn nhịp, hội thảo sự kiện đông đúc hoặc sự cởi mở giao tiếp thu hút công chúng tốt lành.',
    meaningReversed: 'Trạng thái ngược chỉ sự e ngại đám đông tự cô lập, bê bối hình ảnh công chúng hoặc sự kiện ngoài trời bị hủy bỏ.',
    imagePath: '/Lenormand/S08.png' // 8 of Spades
  },
  {
    id: 21,
    slug: 'mountain',
    nameEn: 'Mountain',
    nameVi: 'Ngọn Núi',
    arcana: 'major',
    number: '21',
    keywordsVi: ['rào cản lớn', 'thử thách kiên nhẫn', 'trì trệ bế tắc', 'sự kiên cố'],
    meaningUpright: 'Ngọn Núi sừng sững chỉ ra rào cản thách thức lớn chắn lối đi của bạn, đòi hỏi sự kiên nhẫn tích lũy nội lực vượt qua thay vì nôn nóng.',
    meaningReversed: 'Trạng thái ngược chỉ khó khăn bế tắc bắt đầu được khai thông, bạn tìm thấy lối đi ngách vượt qua ngọn núi cản trở.',
    imagePath: '/Lenormand/C08.png' // 8 of Clubs
  },
  {
    id: 22,
    slug: 'crossroads',
    nameEn: 'Crossroads',
    nameVi: 'Ngã Rẽ',
    arcana: 'major',
    number: '22',
    keywordsVi: ['quyết định ngã rẽ', 'nhiều lựa chọn giải pháp', 'tự do ý chí', 'bước ngoặt'],
    meaningUpright: 'Ngã Rẽ biểu thị thời điểm buộc phải đưa ra quyết định lựa chọn hướng đi cụ thể. Bạn có quyền tự do lựa chọn giải pháp phù hợp nhất.',
    meaningReversed: 'Trạng thái ngược chỉ sự hoang mang không dám chọn lựa dẫn đến dậm chân tại chỗ, hoặc quyết định sai lầm do bốc đồng.',
    imagePath: '/Lenormand/D12.png' // Queen of Diamonds
  },
  {
    id: 23,
    slug: 'mice',
    nameEn: 'Mice',
    nameVi: 'Lũ Chuột',
    arcana: 'major',
    number: '23',
    keywordsVi: ['mất mát hao mòn', 'lo lắng gặm nhấm', 'sự phá hoại ngầm', 'bệnh dịch'],
    meaningUpright: 'Lũ Chuột cảnh báo sự thất thoát của cải hao mòn dần dần, những lo lắng nhỏ gặm nhấm tâm hồn hay sự phá hoại ngầm từ những chi tiết nhỏ.',
    meaningReversed: 'Trạng thái ngược chỉ sự thất thoát được ngăn chặn kịp thời, mối lo âu dần nguôi ngoai và bắt đầu thu dọn khắc phục thiệt hại.',
    imagePath: '/Lenormand/C07.png' // 7 of Clubs
  },
  {
    id: 24,
    slug: 'heart',
    nameEn: 'Heart',
    nameVi: 'Trái Tim',
    arcana: 'major',
    number: '24',
    keywordsVi: ['tình yêu nồng cháy', 'cảm xúc chân thành', 'hài lòng đam mê', 'sự hòa hợp cảm xúc'],
    meaningUpright: 'Trái Tim đỏ thắm mang năng lượng tình yêu nồng cháy, cảm xúc chân thành gắn kết đôi bên và sự hài lòng trọn vẹn trong các mối quan hệ đời sống.',
    meaningReversed: 'Trạng thái ngược chỉ sự hờ hững lạnh nhạt dần phát sinh, tổn thương tình cảm rạn nứt kết nối do ích kỷ.',
    imagePath: '/Lenormand/H11.png' // Jack of Hearts
  },
  {
    id: 25,
    slug: 'ring',
    nameEn: 'Ring',
    nameVi: 'Chiếc Nhẫn',
    arcana: 'major',
    number: '25',
    keywordsVi: ['cam kết hợp đồng', 'hôn ước gắn kết', 'vòng lặp chu kỳ', 'đối tác đáng tin'],
    meaningUpright: 'Chiếc Nhẫn tượng trưng cho hợp đồng giao ước kinh doanh, cam kết hôn nhân bền vững lâu dài và sự tuần hoàn trọn vẹn tốt đẹp.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự phá vỡ hợp đồng cam kết, ly hôn rạn nứt mối quan hệ đối tác hoặc vòng lặp tiêu cực bế tắc.',
    imagePath: '/Lenormand/C01.png' // Ace of Clubs
  },
  {
    id: 26,
    slug: 'book',
    nameEn: 'Book',
    nameVi: 'Cuốn Sách',
    arcana: 'major',
    number: '26',
    keywordsVi: ['bí mật học vấn', 'tri thức ẩn giấu', 'điều tra nghiên cứu', 'sự thật chưa mở'],
    meaningUpright: 'Cuốn Sách đóng kín biểu thị tri thức chuyên sâu ẩn giấu, bí mật đời tư chưa hiển lộ hoặc quá trình học hành nghiên cứu điều tra sâu rộng.',
    meaningReversed: 'Trạng thái ngược chỉ bí mật bị khui mở phơi bày ra ánh sáng, sự thật sáng tỏ hoặc việc học hành thi cử gặp trắc trở nhẹ.',
    imagePath: '/Lenormand/D10.png' // 10 of Diamonds
  },
  {
    id: 27,
    slug: 'letter',
    nameEn: 'Letter',
    nameVi: 'Lá Thư',
    arcana: 'major',
    number: '27',
    keywordsVi: ['tin nhắn giấy tờ', 'hồ sơ pháp lý', 'thông điệp văn bản', 'tin tức bằng chữ'],
    meaningUpright: 'Lá Thư đại diện cho tin tức bằng văn bản cụ thể, thư điện tử, hợp đồng giấy tờ ký kết hoặc hồ sơ pháp lý cần xử lý.',
    meaningReversed: 'Trạng thái ngược chỉ thư từ bị thất lạc, rắc rối sai sót giấy tờ thủ tục hành chính hoặc tin tức từ chối bất lợi.',
    imagePath: '/Lenormand/S07.png' // 7 of Spades
  },
  {
    id: 28,
    slug: 'man',
    nameEn: 'Man',
    nameVi: 'Người Nam',
    arcana: 'major',
    number: '28',
    keywordsVi: ['seeker nam', 'người nam quan trọng', 'năng lượng nam tính', 'chủ động'],
    meaningUpright: 'Đại diện cho chính người hỏi bài (nếu là nam) hoặc người đàn ông quan trọng có tầm ảnh hưởng lớn trong cuộc sống của quý nhân.',
    meaningReversed: 'Năng lượng nam tính bị bóp méo: sự hung hăng chuyên quyền thô bạo, hoặc ngược lại là sự thiếu quyết đoán nhu nhược yếu hèn.',
    imagePath: '/Lenormand/H01.png' // Ace of Hearts
  },
  {
    id: 29,
    slug: 'woman',
    nameEn: 'Woman',
    nameVi: 'Người Nữ',
    arcana: 'major',
    number: '29',
    keywordsVi: ['seeker nữ', 'người nữ quan trọng', 'năng lượng nữ tính', 'thụ động'],
    meaningUpright: 'Đại diện cho chính người hỏi bài (nếu là nữ) hoặc người phụ nữ quan trọng (vợ, người yêu, mẹ) có tầm ảnh hưởng lớn trong hoàn cảnh của bạn.',
    meaningReversed: 'Năng lượng nữ tính bị tắc nghẽn: tính chiếm hữu cao ghen tuông đố kỵ ngầm, hoặc sự phụ thuộc yếu đuối cảm xúc.',
    imagePath: '/Lenormand/S01.png' // Ace of Spades
  },
  {
    id: 30,
    slug: 'lily',
    nameEn: 'Lily',
    nameVi: 'Hoa Huệ',
    arcana: 'major',
    number: '30',
    keywordsVi: ['thuần khiết bình yên', 'người lớn tuổi thông thái', 'sự trưởng thành', 'hài hòa lâu dài'],
    meaningUpright: 'Hoa Huệ biểu thị sự thuần khiết bình yên nội tâm sâu sắc, sự hỗ trợ từ người lớn tuổi thông thái và cuộc sống hài hòa hạnh phúc viên mãn tuổi xế chiều.',
    meaningReversed: 'Trạng thái ngược chỉ sự bất hòa trong gia đình lớn, mất mát danh dự cá nhân hoặc mâu thuẫn thế hệ kéo dài.',
    imagePath: '/Lenormand/S13.png' // King of Spades
  },
  {
    id: 31,
    slug: 'sun',
    nameEn: 'Sun',
    nameVi: 'Mặt Trời',
    arcana: 'major',
    number: '31',
    keywordsVi: ['vinh quang rực rỡ', 'thành công vang dội', 'sinh khí tràn đầy', 'may mắn tối thượng'],
    meaningUpright: 'Mặt Trời mang may mắn tối thượng chiếu sáng vương quốc của bạn. Báo hiệu thành công vang dội, sức khỏe sinh khí tràn đầy và mọi điều tăm tối biến mất.',
    meaningReversed: 'Trạng thái ngược chỉ sự thành công bị cản trở trì hoãn tạm thời, hoặc năng lượng sinh khí bị suy giảm nhẹ không đáng kể.',
    imagePath: '/Lenormand/D01.png' // Ace of Diamonds
  },
  {
    id: 32,
    slug: 'moon',
    nameEn: 'Moon',
    nameVi: 'Mặt Trăng',
    arcana: 'major',
    number: '32',
    keywordsVi: ['danh tiếng xã hội', 'cảm xúc tiềm thức', 'trực giác nhạy bén', 'sự phản chiếu'],
    meaningUpright: 'Mặt Trăng đại diện cho danh tiếng xã hội vang xa, trực giác tâm linh nhạy bén và dòng chảy cảm xúc lãng mạn dạt dào nội tâm.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự bất ổn tâm lý lo âu phi lý, tiếng tăm bị ảnh hưởng xấu hoặc sự ngộ nhận ảo tưởng cảm xúc.',
    imagePath: '/Lenormand/H08.png' // 8 of Hearts
  },
  {
    id: 33,
    slug: 'key',
    nameEn: 'Key',
    nameVi: 'Chìa Khóa',
    arcana: 'major',
    number: '33',
    keywordsVi: ['giải pháp giải quyết', 'chìa khóa thành công', 'sự chắc chắn tuyệt đối', 'mở ra cánh cửa'],
    meaningUpright: 'Chìa Khóa mang đến giải pháp tháo gỡ bế tắc triệt để. Mở ra cánh cửa cơ hội mới tốt đẹp với sự chắc chắn thành công tuyệt đối.',
    meaningReversed: 'Trạng thái ngược chỉ giải pháp bị bế tắc chưa tìm ra hướng đi, cơ hội bị khóa kín tạm thời do thiếu chuẩn bị.',
    imagePath: '/Lenormand/D08.png' // 8 of Diamonds
  },
  {
    id: 34,
    slug: 'fish',
    nameEn: 'Fish',
    nameVi: 'Đàn Cá',
    arcana: 'major',
    number: '34',
    keywordsVi: ['tiền bạc dồi dào', 'giao thương thịnh vượng', 'dòng tài sản chu chuyển', 'sự phong phú'],
    meaningUpright: 'Đàn Cá bơi lội biểu thị dòng tiền bạc của cải chu chuyển dồi dào trôi chảy, kinh doanh giao thương thịnh vượng mang lại lợi nhuận lớn.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói chi tiêu hoang phí thất thoát tài chính, đầu tư rủi ro thua lỗ tạm thời.',
    imagePath: '/Lenormand/D13.png' // King of Diamonds
  },
  {
    id: 35,
    slug: 'anchor',
    nameEn: 'Anchor',
    nameVi: 'Mỏ Neo',
    arcana: 'major',
    number: '35',
    keywordsVi: ['ổn định lâu dài', 'mục tiêu vững chắc', 'sự an lòng', 'nghề nghiệp bền vững'],
    meaningUpright: 'Mỏ Neo cắm sâu mang lại sự an lòng ổn định lâu dài trong công việc nghề nghiệp và các cam kết quan trọng của cuộc đời.',
    meaningReversed: 'Trạng thái ngược chỉ sự gò bó ngột ngạt không thể bứt phá, hoặc tình trạng mất ổn định chao đảo ngoài tầm kiểm soát.',
    imagePath: '/Lenormand/S09.png' // 9 of Spades
  },
  {
    id: 36,
    slug: 'cross',
    nameEn: 'Cross',
    nameVi: 'Thập Tự',
    arcana: 'major',
    number: '36',
    keywordsVi: ['gánh nặng gánh vác', 'thử thách số phận', 'sự đau buồn', 'niềm tin tôn giáo'],
    meaningUpright: 'Thập Tự biểu thị gánh nặng số phận bạn phải kiên cường gánh vác để vượt qua bài học chuyển hóa lớn lao của linh hồn. Hãy kiên tâm giữ vững niềm tin.',
    meaningReversed: 'Trạng thái ngược chỉ sự giảm nhẹ bớt nỗi đau gánh nặng, tìm thấy sự cứu rỗi hoặc vượt qua bài học số phận thành công.',
    imagePath: '/Lenormand/C06.png' // 6 of Clubs
  }
];

export function getCardById(id: number): TarotCard | undefined {
  return lenormandCards.find((card) => card.id === id);
}

export function getCardBySlug(slug: string): TarotCard | undefined {
  return lenormandCards.find((card) => card.slug === slug);
}
