import { TarotCard } from './cards-data';

export const marseilleCards: TarotCard[] = [
  // MAJOR ARCANA (0-21)
  {
    id: 0,
    slug: 'le-mat',
    nameEn: 'Le Mat',
    nameVi: 'Kẻ Lữ Hành',
    arcana: 'major',
    number: '0',
    keywordsVi: ['lữ hành tự do', 'bản năng dẫn lối', 'khởi đầu vô định', 'kẻ điên', 'vô tư lự'],
    meaningUpright: 'Le Mat là người lữ hành vác hành lý trên vai, bước đi vô định không màng quá khứ hay tương lai, theo sau là chú chó thúc giục bản năng. Đây là biểu tượng của tinh thần tự do tối thượng, hành động thuần túy theo trực giác mà không bị rào cản luân lý hay xã hội ràng buộc.',
    meaningReversed: 'Trạng thái ngược chỉ sự phiêu lưu vô trách nhiệm, điên rồ mù quáng hoặc từ chối hành động do e sợ rủi ro. Bạn có thể đang lạc lối do thiếu đi sự tỉnh táo cơ bản.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-00-le-mat_6244474908_l.jpg'
  },
  {
    id: 1,
    slug: 'le-bateleur',
    nameEn: 'Le Bateleur',
    nameVi: 'Nhà Ảo Thuật',
    arcana: 'major',
    number: '1',
    keywordsVi: ['khéo léo', 'bắt đầu hành động', 'tiềm năng sẵn có', 'sự sáng tạo', 'ảo thuật'],
    meaningUpright: 'Le Bateleur đứng trước chiếc bàn chứa các công cụ đại diện cho các chất bài. Anh ta là người khởi sự đầy nhiệt huyết, khéo léo và mang tiềm năng vô hạn để hiện thực hóa các ý tưởng sáng tạo bằng chính đôi tay của mình.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự lừa bịp, ảo tưởng tự phụ hoặc lãng phí tài năng thực tế do thiếu kiên trì. Một sự bắt đầu vụng về hoặc ý đồ thao túng không lành mạnh.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-01-le-bateleur_6243960859_l.jpg'
  },
  {
    id: 2,
    slug: 'la-papesse',
    nameEn: 'La Papesse',
    nameVi: 'Nữ Giáo Hoàng',
    arcana: 'major',
    number: '2',
    keywordsVi: ['tĩnh lặng', 'tri thức ẩn giấu', 'trực giác thụ động', 'sự kiên nhẫn', 'bí mật'],
    meaningUpright: 'La Papesse ngồi lặng lẽ giữ cuốn sách đóng kín trên tay, biểu thị tri thức huyền học sâu kín và trực giác thụ động. Lá bài khuyên bạn hãy kiên nhẫn tích lũy, nhìn nhận bản chất sự việc thay vì vội vã phán xét hay hành động.',
    meaningReversed: 'Trạng thái ngược cho thấy sự lạnh lùng ích kỷ, định kiến bảo thủ hoặc sự nghi ngờ trực giác của chính mình. Những bí mật độc hại có nguy cơ bị phanh phui.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-02-la-papesse_6243964417_l.jpg'
  },
  {
    id: 3,
    slug: 'limperatrice',
    nameEn: "L'Impératrice",
    nameVi: 'Nữ Hoàng',
    arcana: 'major',
    number: '3',
    keywordsVi: ['trù phú', 'quyền năng sáng tạo', 'thiên chức làm mẹ', 'sự phát triển', 'nữ tính'],
    meaningUpright: 'L\'Impératrice cầm tấm khiên hoàng gia biểu thị sự sinh trưởng, quyền năng cai quản trần thế bằng tình thương và sự trù phú vật chất. Nguồn năng lượng tích cực thúc đẩy sự phát triển của vạn vật và nghệ thuật.',
    meaningReversed: 'Trạng thái ngược chỉ sự kiêu ngạo, tính chiếm hữu quá mức hoặc tình trạng trì trệ trong sáng tạo. Bạn có thể đang gặp khó khăn trong việc nuôi dưỡng cảm xúc.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-03-limperatrice_6243968475_l.jpg'
  },
  {
    id: 4,
    slug: 'lempereur',
    nameEn: "L'Empereur",
    nameVi: 'Hoàng Đế',
    arcana: 'major',
    number: '4',
    keywordsVi: ['trật tự vững chắc', 'quyền lực kỷ luật', 'kiến thiết thực tế', 'bảo vệ', 'nam tính'],
    meaningUpright: 'L\'Empereur ngồi vững chãi cầm quyền trượng vương quyền, biểu thị cấu trúc trật tự xã hội bền vững và khả năng bảo vệ vương quốc. Lá bài đại diện cho tư duy thực tế, tính kỷ luật tự chủ và hành động kiến thiết bền bỉ.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói bạo chúa, độc đoán cứng nhắc gây ngột ngạt, hoặc sự yếu nhược, mất kiểm soát trong việc quản lý công việc đời sống.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-04-lempereur_6243971967_l.jpg'
  },
  {
    id: 5,
    slug: 'le-pape',
    nameEn: 'Le Pape',
    nameVi: 'Giáo Hoàng',
    arcana: 'major',
    number: '5',
    keywordsVi: ['truyền thống', 'dạy bảo thông thái', 'hòa giải tâm linh', 'đức tin', 'sự chỉ dẫn'],
    meaningUpright: 'Le Pape giơ tay ban phước lành cho các đệ tử, đóng vai trò cầu nối trung gian hòa giải giữa trần thế và tâm linh thần thánh. Lá bài hướng tới việc tôn trọng truyền thống đạo đức, học hỏi từ vị thầy thông thái và củng cố đức tin.',
    meaningReversed: 'Trạng thái ngược chỉ sự giáo điều cứng nhắc, thói giả tạo nhân danh đạo đức hoặc sự nổi loạn chống lại các cấu trúc xã hội truyền thống một cách vô lý.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-05-le-pape_6244493710_l.jpg'
  },
  {
    id: 6,
    slug: 'lamoureux',
    nameEn: "L'Amoureux",
    nameVi: 'Đôi Nhân Tình',
    arcana: 'major',
    number: '6',
    keywordsVi: ['sự chọn lựa', 'tình cảm đôi lứa', 'sự thu hút', 'thử thách lòng tin', 'hài hòa'],
    meaningUpright: 'L\'Amoureux mô tả chàng trai đứng giữa hai người phụ nữ dưới sự dẫn dắt của thần tình yêu Cupid trên cao. Lá bài nói về những lựa chọn mang tính bước ngoặt cuộc đời, đòi hỏi sự dung hòa giữa ham muốn bản năng và lý trí đạo đức.',
    meaningReversed: 'Trạng thái ngược phản ánh sự bất hòa trong tình cảm, lựa chọn sai lầm do bốc đồng cảm xúc hoặc sự chia rẽ nội tâm sâu sắc không thể hàn gắn.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-06-lamoureux_6244497460_l.jpg'
  },
  {
    id: 7,
    slug: 'le-chariot',
    nameEn: 'Le Chariot',
    nameVi: 'Chiến Xa',
    arcana: 'major',
    number: '7',
    keywordsVi: ['chiến thắng hiển hách', 'ý chí chinh phục', 'lãnh đạo quyết đoán', 'đoàn kết đối lập', 'tiến lên'],
    meaningUpright: 'Le Chariot di chuyển dưới sự kéo của hai con ngựa ngược hướng nhưng cùng chịu sự kiểm soát của vị tướng tài ba. Lá bài ca ngợi sức mạnh của ý chí vượt khó, lòng dũng cảm tiến lên và khả năng lãnh đạo làm chủ tình hình.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự mất phương hướng, kiêu căng ngạo mạn dẫn đến tai nạn, hoặc sự tranh giành quyền lực nội bộ khiến cỗ xe sụp đổ.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-07-le-chariot_6244501376_l.jpg'
  },
  {
    id: 8,
    slug: 'la-justice',
    nameEn: 'La Justice',
    nameVi: 'Công Lý',
    arcana: 'major',
    number: '8',
    keywordsVi: ['luật lệ công bằng', 'phán quyết khách quan', 'thăng bằng nhân quả', 'sự trung thực', 'cắt bỏ thiên vị'],
    meaningUpright: 'La Justice cầm gươm và cân công lý đứng thẳng biểu thị phán quyết minh bạch, sòng phẳng tuyệt đối. Mọi hành động của bạn đều sẽ nhận lại kết quả công minh tương xứng theo quy luật nhân quả của vũ trụ.',
    meaningReversed: 'Trạng thái ngược thể hiện sự thiên vị, định kiến bất công hoặc thói trốn tránh trách nhiệm. Bạn có thể đang nhận lấy những phán quyết bất lợi do sai phạm quá khứ.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-08-la-justice_6243987723_l.jpg'
  },
  {
    id: 9,
    slug: 'lhermite',
    nameEn: "L'Hermite",
    nameVi: 'Ẩn Sĩ',
    arcana: 'major',
    number: '9',
    keywordsVi: ['soi đường tìm lối', 'sự cô độc tự suy', 'sự trưởng thành chậm rãi', 'thông thái', 'bảo mật'],
    meaningUpright: 'L\'Hermite cầm ngọn đèn phủ áo choàng bước đi chậm rãi ngược dòng thời gian để tự suy ngẫm. Lá bài khuyên bạn nên tạm lánh xa ồn ào xã hội, tĩnh tâm nghiên cứu và tìm kiếm câu trả lời thông thái từ bên trong tâm hồn.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự cô độc bệnh lý tự giam cầm bản thân, sự lập dị từ chối giúp đỡ từ người khác hoặc sự trì hoãn lãng phí thời gian vô bổ.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-09-lhermite_6243991937_l.jpg'
  },
  {
    id: 10,
    slug: 'la-roue-de-fortune',
    nameEn: 'La Roue de Fortune',
    nameVi: 'Vòng Vận Mệnh',
    arcana: 'major',
    number: '10',
    keywordsVi: ['xoay vần số phận', 'sự thay đổi chu kỳ', 'cơ hội bất ngờ', 'vận may thế gian', 'vô thường'],
    meaningUpright: 'La Roue de Fortune mô tả vòng quay với các sinh vật leo lên lộn xuống, nhắc nhở ta về tính vô thường của vương quyền vật chất thế gian. Một bước ngoặt lớn sắp sửa diễn ra mang tính chất nhân quả.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự xui xẻo do cưỡng lại quy luật thay đổi tự nhiên, hoặc thói đầu cơ mạo hiểm vô căn cứ dẫn đến thất bại nặng nề.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-10-la-roue-de-fortune_6244512804_l.jpg'
  },
  {
    id: 11,
    slug: 'la-force',
    nameEn: 'La Force',
    nameVi: 'Sức Mạnh',
    arcana: 'major',
    number: '11',
    keywordsVi: ['chế ngự bản năng', 'lòng dũng cảm mềm mại', 'sự tự tin', 'kiên trì nội tại', 'sức bền'],
    meaningUpright: 'La Force dùng tay khống chế hàm sư tử một cách nhẹ nhàng uyển chuyển mà không cần bạo lực vũ khí. Đây là biểu tượng của sức mạnh tinh thần vượt trội, lòng kiên trì và khả năng chế ngự bản năng hoang dã bằng tình thương.',
    meaningReversed: 'Trạng thái ngược thể hiện sự bất lực kiệt quệ năng lượng sống, hoặc ngược lại là hành động hung hăng thô bạo lạm dụng quyền lực gây tổn hại nghiêm trọng.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-11-la-force_6243998967_l.jpg'
  },
  {
    id: 12,
    slug: 'le-pendu',
    nameEn: 'Le Pendu',
    nameVi: 'Người Treo',
    arcana: 'major',
    number: '12',
    keywordsVi: ['hiến tế cái tôi', 'tĩnh lặng chờ đợi', 'đảo ngược góc nhìn', 'chấp nhận số phận', 'trì hoãn'],
    meaningUpright: 'Le Pendu bị treo ngược một chân lên cành cây nhưng gương mặt hoàn toàn thanh thản tĩnh lặng. Lá bài dạy ta bài học về sự hiến tế, buông bỏ mong muốn kiểm soát để nhìn nhận thế giới từ một góc độ hoàn toàn mới.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự hy sinh vô ích, trạng thái bế tắc kéo dài do ngoan cố bám víu vào cái tôi cũ kỹ, e sợ hành động đột phá giải phóng.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-12-le-pendu_6244002027_l.jpg'
  },
  {
    id: 13,
    slug: 'la-mort',
    nameEn: 'La Mort',
    nameVi: 'Lá Bài Không Tên',
    arcana: 'major',
    number: '13',
    keywordsVi: ['cắt bỏ triệt để', 'sự chuyển hóa lớn', 'kết thúc bắt buộc', 'giải phóng đất đai', 'tái sinh'],
    meaningUpright: 'La Mort (thường không đề tên trong Marseille) mô tả bộ xương cầm lưỡi hái cắt đứt cỏ khô gieo mầm sống mới. Lá bài báo hiệu sự kết thúc triệt để của cấu trúc cũ kỹ lỗi thời để nhường chỗ cho sự tái sinh huy hoàng mới.',
    meaningReversed: 'Trạng thái ngược cho thấy sự e sợ thay đổi cố chấp bám víu lấy những thứ đã chết mòn năng lượng, hoặc trạng thái u uất kéo dài do không chịu buông xả.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-13-la-mort_6244522256_l.jpg'
  },
  {
    id: 14,
    slug: 'temperance',
    nameEn: 'La Tempérance',
    nameVi: 'Sự Tiết Độ',
    arcana: 'major',
    number: '14',
    keywordsVi: ['dung hòa cảm xúc', 'dòng chảy điều hòa', 'chữa lành', 'sự chừng mực', 'kiên nhẫn'],
    meaningUpright: 'La Tempérance rót dòng nước sự sống chu chuyển liên tục qua lại giữa hai chiếc bình vàng bạc. Lá bài mang thông điệp chữa lành tổn thương tinh thần, dung hòa các dòng chảy đối lập để tìm lại sự bình yên chừng mực.',
    meaningReversed: 'Trạng thái ngược chỉ sự mất cân đối năng lượng sống, lối sống thái quá thiếu lành mạnh hoặc xung đột giao tiếp do bất đồng quan điểm cứng nhắc.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-14-temperance_6244008423_l.jpg'
  },
  {
    id: 15,
    slug: 'le-diable',
    nameEn: 'Le Diable',
    nameVi: 'Ác Quỷ',
    arcana: 'major',
    number: '15',
    keywordsVi: ['trói buộc vật chất', 'cám dỗ bản năng', 'thống trị dục vọng', 'mê muội', 'sức hút ma lực'],
    meaningUpright: 'Le Diable đứng trên bục thống trị hai tiểu quỷ bị xích cổ biểu thị sức hút mãnh liệt của tiền tài, danh vọng và dục vọng trần thế. Lá bài nhắc nhở bạn cần đối diện thẳng thắn với những ham muốn và sự trói buộc nội tâm.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự thức tỉnh giải phóng bản thân thoát khỏi các thói quen nghiện ngập độc hại, hoặc sự sa đọa lún sâu vào bóng tối vật chất.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-15-le-diable_6244530490_l.jpg'
  },
  {
    id: 16,
    slug: 'la-maison-dieu',
    nameEn: 'La Maison Dieu',
    nameVi: 'Tòa Nhà Của Chúa',
    arcana: 'major',
    number: '16',
    keywordsVi: ['hủy diệt kiêu ngạo', 'giải phóng đột ngột', 'sụp đổ ảo tưởng', 'bừng tỉnh nhận thức', 'chấn động'],
    meaningUpright: 'La Maison Dieu mô tả tòa tháp bị tia sét thiên đình đánh bật vương miện kiêu hãnh. Đây là sự sụp đổ bất ngờ vô cùng đau đớn nhưng cần thiết để đập tan mọi ảo tưởng ngạo mạn tự phụ của con người.',
    meaningReversed: 'Trạng thái ngược chỉ ra thảm họa kéo dài âm ỉ không dứt, hoặc nỗ lực tuyệt vọng bám víu pháo đài mục nát chống lại sự thay đổi vũ trụ.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-16-la-maison-dieu_6244534846_l.jpg'
  },
  {
    id: 17,
    slug: 'letoile',
    nameEn: "L'Étoile",
    nameVi: 'Ngôi Sao',
    arcana: 'major',
    number: '17',
    keywordsVi: ['hi vọng phục hồi', 'thanh lọc tâm hồn', 'hào phóng hiến dâng', 'sự chỉ dẫn thiên nhiên', 'niềm tin'],
    meaningUpright: 'L\'Étoile mô tả cô gái khỏa thân đổ nước ngọt lành xuống đất và sông dưới bầu trời sao rực rỡ. Lá bài đem lại niềm tin phục hồi, hi vọng ngập tràn sau khủng hoảng và lòng hào phóng chia sẻ tài nguyên rộng mở.',
    meaningReversed: 'Trạng thái ngược thể hiện sự thất vọng bi quan e sợ tương lai, sự cạn kiệt niềm tin hoặc cảm giác cô độc không có ai định hướng trợ lực.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-17-letoile_6244021511_l.jpg'
  },
  {
    id: 18,
    slug: 'la-lune',
    nameEn: 'La Lune',
    nameVi: 'Mặt Trăng',
    arcana: 'major',
    number: '18',
    keywordsVi: ['ảo giác mịt mờ', 'nỗi sợ tiềm thức', 'sự lừa dối tinh vi', 'bản năng trỗi dậy', 'hành trình bóng tối'],
    meaningUpright: 'La Lune mô tả chú tôm hông nhô lên từ hồ nước sâu thẳm dưới ánh trăng mờ ảo cùng hai chú chó sủa bóng đêm. Lá bài chỉ ra giai đoạn mịt mờ đầy ảo giác lừa dối, khuyên bạn tin vào bản năng hoang dã bảo vệ mình.',
    meaningReversed: 'Trạng thái ngược báo hiệu ảo ảnh bắt đầu tan biến nhường chỗ cho sự thật phơi bày, hoặc sự bất ổn tâm lý nghiêm trọng bộc phát kéo dài.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-18-la-lune_6244543754_l.jpg'
  },
  {
    id: 19,
    slug: 'le-soleil',
    nameEn: 'Le Soleil',
    nameVi: 'Mặt Trời',
    arcana: 'major',
    number: '19',
    keywordsVi: ['vinh quang rực rỡ', 'sự sáng suốt tư duy', 'hợp tác chân thành', 'thành công rực rỡ', 'niềm vui trẻ thơ'],
    meaningUpright: 'Le Soleil chiếu rọi những tia sáng đa sắc nuôi dưỡng hai đứa trẻ hòa hợp bên nhau. Lá bài đại diện cho vinh quang thành công rực rỡ, tình bạn tri kỷ chân thành và sự sáng rõ tư duy giúp giải quyết mọi vấn đề tăm tối.',
    meaningReversed: 'Trạng thái ngược chỉ sự kiêu căng khoác lác quá đà, sự thành công bị trì hoãn tạm thời hoặc năng lượng hào quang bị suy giảm nhẹ.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-19-le-soleil_6244031559_l.jpg'
  },
  {
    id: 20,
    slug: 'le-jugement',
    nameEn: 'Le Jugement',
    nameVi: 'Phán Xét',
    arcana: 'major',
    number: '20',
    keywordsVi: ['thức tỉnh tiếng gọi', 'sự tái sinh lớn', 'phán quyết cuối cùng', 'tha thứ', 'bước chuyển vĩ đại'],
    meaningUpright: 'Le Jugement miêu tả thiên thần thổi kèn gọi người chết thức tỉnh trỗi dậy từ nấm mồ. Đây là biểu tượng của việc lắng nghe tiếng gọi thiên liêng của linh hồn, thực hiện bước chuyển hóa vĩ đại tái sinh bản thân.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự phớt lờ tiếng gọi lương tâm, nuối tiếc níu kéo quá khứ phạm sai lầm hoặc e sợ thay đổi lớn lao cần thiết.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-20-le-jugement_6244553092_l.jpg'
  },
  {
    id: 21,
    slug: 'le-monde',
    nameEn: 'Le Monde',
    nameVi: 'Thế Giới',
    arcana: 'major',
    number: '21',
    keywordsVi: ['hoàn thành viên mãn', 'giải phóng vẹn tròn', 'hòa hợp tuyệt đối', 'thành tựu tối thượng', 'đạt đỉnh vinh quang'],
    meaningUpright: 'Le Monde mô tả vũ công đứng giữa vòng nguyệt quế bao quanh bởi bốn biểu tượng sinh vật linh thiêng. Lá bài đại diện cho sự hoàn thành mỹ mãn tối thượng của hành trình đại công trình tâm linh thế gian.',
    meaningReversed: 'Trạng thái ngược chỉ sự e ngại ở bước cuối cùng trước vinh quang, cảm giác thiếu hụt trọn vẹn mặc dù công việc đã đạt được đích đến cơ bản.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-majeurs-21-le-monde_6244557566_l.jpg'
  },

  // MINOR ARCANA (22-77)
  // WANDS (Bâtons) (22-35)
  {
    id: 22,
    slug: 'ace-of-wands',
    nameEn: 'As de Bâton',
    nameVi: 'As de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: 'ace',
    keywordsVi: ['nguồn sống dồi dào', 'ý chí khởi đầu', 'sức mạnh gậy bản nguyên', 'nhiệt huyết'],
    meaningUpright: 'As de Bâton đại diện cho ngọn lửa sinh mệnh sơ khởi rực cháy dưới hình tượng chiếc gậy thô ráp đầy mầm sống. Khởi nguồn của hành động quyết liệt và ý chí kiên cường để bắt đầu các kế hoạch thực tế.',
    meaningReversed: 'Trạng thái ngược phản ánh sự nguội tắt nhiệt huyết đột ngột, năng lượng hành động bị phân tán hoặc sự bắt đầu thiếu chuẩn bị dài hạn.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-01_6244560752_l.jpg'
  },
  {
    id: 23,
    slug: 'two-of-wands',
    nameEn: 'Deux de Bâton',
    nameVi: 'Deux de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: '2',
    keywordsVi: ['cân bằng lực lượng', 'chuẩn bị kế hoạch', 'song hành ý chí', 'suy ngẫm định hướng'],
    meaningUpright: 'Hai chiếc gậy giao nhau biểu thị sự cân bằng lực lượng ý chí sơ khởi. Đây là giai đoạn chuẩn bị kỹ càng, tích lũy năng lượng và định hình hướng đi cụ thể cho dự án tương lai.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự do dự kéo dài làm mất cơ hội, hoặc sự xung đột triệt tiêu năng lượng lẫn nhau giữa hai mục tiêu song hành.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-02_6244046905_l.jpg'
  },
  {
    id: 24,
    slug: 'three-of-wands',
    nameEn: 'Trois de Bâton',
    nameVi: 'Trois de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: '3',
    keywordsVi: ['bước tiến ban đầu', 'sự vững vàng nền tảng', 'khám phá triển vọng', 'ý chí kiên định'],
    meaningUpright: 'Ba chiếc gậy đan xen mở ra hướng đi vững chắc đầu tiên cho hành trình. Ý chí của bạn đã được khẳng định bằng hành động thực tế mang lại kết quả bước đầu khả quan.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự nóng vội gặt hái kết quả non yếu, hoặc kế hoạch bị chững lại do thiếu tầm nhìn chiến lược dài hơi.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-03_6244566788_l.jpg'
  },
  {
    id: 25,
    slug: 'four-of-wands',
    nameEn: 'Quatre de Bâton',
    nameVi: 'Quatre de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: '4',
    keywordsVi: ['ổn định vững chắc', 'hoàn thành cấu trúc', 'bình yên nội tại', 'sự hòa hợp'],
    meaningUpright: 'Bốn chiếc gậy tạo thành cấu trúc vuông vắn vững chãi nhất. Lá bài mang ý nghĩa ổn định cuộc sống, cấu trúc dự án bền vững và sự bình yên nội tại được thiết lập tốt đẹp.',
    meaningReversed: 'Trạng thái ngược chỉ sự tự mãn e ngại thay đổi cần thiết để phát triển tiếp, hoặc cấu trúc bên ngoài bắt đầu rạn nứt nhẹ.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-04_6244569386_l.jpg'
  },
  {
    id: 26,
    slug: 'five-of-wands',
    nameEn: 'Cinq de Bâton',
    nameVi: 'Cinq de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: '5',
    keywordsVi: ['cọ xát cản trở', 'áp lực thử thách', 'xung đột ý kiến', 'đấu tranh nội tâm'],
    meaningUpright: 'Cinq de Bâton mang năng lượng lửa cọ xát tạo ra mâu thuẫn xung đột ý kiến gay gắt. Đây là thử thách lòng kiên trì chịu đựng áp lực để chứng minh năng lực thật sự.',
    meaningReversed: 'Trạng thái ngược thể hiện sự trốn tránh mâu thuẫn dẫn đến ức chế ngầm, hoặc tranh chấp dai dẳng kiệt quệ tài nguyên vô ích.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-05_6244054927_l.jpg'
  },
  {
    id: 27,
    slug: 'six-of-wands',
    nameEn: 'Six de Bâton',
    nameVi: 'Six de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: '6',
    keywordsVi: ['vinh quang chiến thắng', 'sự công nhận xã hội', 'lãnh đạo tin cậy', 'niềm tin mãnh liệt'],
    meaningUpright: 'Sáu chiếc gậy đan xen đối xứng biểu thị chiến thắng huy hoàng sau đấu tranh gian khổ. Bạn nhận được sự công nhận xứng đáng từ tập thể và niềm tin được khôi phục mạnh mẽ.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói ngạo mạn sau chiến thắng ngắn hạn dễ dẫn đến sơ hở, hoặc sự chậm trễ trong việc nhận thưởng công danh.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-06_6244575342_l.jpg'
  },
  {
    id: 28,
    slug: 'seven-of-wands',
    nameEn: 'Sept de Bâton',
    nameVi: 'Sept de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: '7',
    keywordsVi: ['giữ vững lập trường', 'phòng thủ kiên cường', 'đương đầu số đông', 'sức mạnh cá nhân'],
    meaningUpright: 'Bảy chiếc gậy chỉ ra thế trận đứng vững phòng thủ bảo vệ thành quả cá nhân trước áp lực tấn công của số đông bên ngoài. Lòng dũng cảm và vị thế chủ động giúp bạn chiến thắng.',
    meaningReversed: 'Trạng thái ngược chỉ sự mệt mỏi hoang mang nhụt chí trước áp lực dồn dập, hoặc xu hướng phòng thủ cực đoan đa nghi vô cớ.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-07_6244578462_l.jpg'
  },
  {
    id: 29,
    slug: 'eight-of-wands',
    nameEn: 'Huit de Bâton',
    nameVi: 'Huit de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: '8',
    keywordsVi: ['tốc độ chuyển dịch', 'hành động đồng loạt', 'tin tức mau lẹ', 'mục tiêu sáng tỏ'],
    meaningUpright: 'Tám chiếc gậy lao nhanh song hành biểu thị tốc độ tiến triển vượt bậc của các kế hoạch. Mọi hoài nghi được xóa bỏ, nhường chỗ cho hành động nhanh chóng đạt mục tiêu.',
    meaningReversed: 'Trạng thái ngược chỉ sự vội vã cẩu thả làm hỏng đại sự, thông tin liên lạc bị tắc nghẽn chậm trễ gây bức bối.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-08_6244064277_l.jpg'
  },
  {
    id: 30,
    slug: 'nine-of-wands',
    nameEn: 'Neuf de Bâton',
    nameVi: 'Neuf de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: '9',
    keywordsVi: ['sự sẵn sàng tối đa', 'kiên cường chặng cuối', 'kinh nghiệm xương máu', 'sức bền bỉ'],
    meaningUpright: 'Chín chiếc gậy đan xen kiên cố đại diện cho sự kiên cường bền bỉ chặng cuối cùng. Bạn tích lũy đủ kinh nghiệm xương máu để sẵn sàng ứng phó biến cố bất ngờ.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự kiệt sức do quá căng thẳng kéo dài, hoặc sự đa nghi tự vệ thái quá dựng rào cản ngăn ngừa cơ hội mới.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-09_6244584478_l.jpg'
  },
  {
    id: 31,
    slug: 'ten-of-wands',
    nameEn: 'Dix de Bâton',
    nameVi: 'Dix de Bâton',
    arcana: 'minor',
    suit: 'wands',
    number: '10',
    keywordsVi: ['gánh nặng đè vai', 'quá tải trách nhiệm', 'ý chí bị đè nén', 'cố gắng quá sức'],
    meaningUpright: 'Dix de Bâton biểu thị mười chiếc gậy đè nặng dồn nén ý chí hành động. Gánh nặng trách nhiệm quá lớn khiến bạn cảm thấy mệt mỏi rã rời. Cần học cách buông bỏ chia sẻ.',
    meaningReversed: 'Trạng thái ngược chỉ sự sụp đổ kiệt quệ hoàn toàn dưới áp lực cực lớn, hoặc quyết định sáng suốt trút bỏ bớt gánh nặng vô ích.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-10_6244069773_l.jpg'
  },
  {
    id: 32,
    slug: 'valet-de-baton',
    nameEn: 'Valet de Bâton',
    nameVi: 'Valet Gậy',
    arcana: 'minor',
    suit: 'wands',
    number: '11',
    keywordsVi: ['tin tức hành động', 'nhiệt huyết trẻ tuổi', 'khao khát học hỏi', 'sự bốc đồng'],
    meaningUpright: 'Valet de Bâton đại diện cho người đưa tin mang nhiệt huyết cháy bỏng, sẵn sàng dấn thân vào các cuộc phiêu lưu mới bằng khao khát học hỏi khám phá mãnh liệt.',
    meaningReversed: 'Trạng thái ngược chỉ tính khí bốc đồng thiếu chín chắn làm hỏng việc, tin tức trì trệ thất vọng hoặc thói kiêu căng ngạo mạn.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-11-valet-de-bton_6244591684_l.jpg'
  },
  {
    id: 33,
    slug: 'cavalier-de-baton',
    nameEn: 'Cavalier de Bâton',
    nameVi: 'Cavalier Gậy',
    arcana: 'minor',
    suit: 'wands',
    number: '12',
    keywordsVi: ['chinh phục bão táp', 'hành động thần tốc', 'tự tin tỏa sáng', 'nóng nảy'],
    meaningUpright: 'Cavalier de Bâton cưỡi ngựa lao nhanh kiêu hãnh đại diện cho hành động thần tốc quyết đoán, tinh thần chinh phục rực cháy và sự tự tin thu hút mãnh liệt.',
    meaningReversed: 'Trạng thái ngược cảnh báo hành động nông nổi liều lĩnh bất chấp hiểm nguy, tính khí nóng nảy phá hỏng mối quan hệ tốt đẹp.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-12-cavalier-de-bton_6244078709_l.jpg'
  },
  {
    id: 34,
    slug: 'queen-of-wands',
    nameEn: 'Reyne de Bâton',
    nameVi: 'Reyne Gậy',
    arcana: 'minor',
    suit: 'wands',
    number: '13',
    keywordsVi: ['sức hút quý phái', 'ấm áp che chở', 'lòng tự trọng cao', 'kiến tạo thực tế'],
    meaningUpright: 'Reyne de Bâton hiện thân của người phụ nữ mang sức hút cá nhân rực rỡ, lòng tự tôn cao quý và khả năng kiến tạo cuộc sống độc lập bằng sự ấm áp bao dung rộng mở.',
    meaningReversed: 'Trạng thái ngược thể hiện sự đố kỵ ghen ghét âm thầm, thói ích kỷ thích kiểm soát thống trị hoặc thói thảo mai lừa dối người khác.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-13-reyne-de-bton_6244599904_l.jpg'
  },
  {
    id: 35,
    slug: 'knight-of-wands',
    nameEn: 'Roy de Bâton',
    nameVi: 'Roy Gậy',
    arcana: 'minor',
    suit: 'wands',
    number: '14',
    keywordsVi: ['nhà lãnh đạo uy nghiêm', 'ý chí kiến quốc', 'quyết đoán thực tế', 'bảo thủ quyền lực'],
    meaningUpright: 'Roy de Bâton (tương đương King of Wands) ngự trị uy nghiêm trên ngai vàng biểu thị ý chí kiên định cai trị vương quốc bằng kỷ luật và tầm nhìn thực tế kiến tạo rộng lớn.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói bạo chúa chuyên quyền bảo thủ cứng nhắc, phản ứng giận dữ lạm dụng quyền uy gây oán hận.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-btons-14-roy-de-bton_6244603754_l.jpg'
  },

  // CUPS (Coupes) (36-49)
  {
    id: 36,
    slug: 'ace-of-cups',
    nameEn: 'As de Coupe',
    nameVi: 'As de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: 'ace',
    keywordsVi: ['tình yêu ngập tràn', 'khởi nguồn cảm xúc', 'trực giác nhạy bén', 'bình yên nội tại'],
    meaningUpright: 'As de Coupe mô tả chiếc cúp thánh cổ điển chứa đựng dòng nước tình cảm thuần khiết dồi dào. Đây là biểu tượng của khởi đầu tình yêu chân thành, cảm xúc ngập tràn và trực giác tâm hồn thức tỉnh.',
    meaningReversed: 'Trạng thái ngược chỉ sự cạn kiệt cảm xúc bên trong, cảm giác trống rỗng cô đơn e sợ bày tỏ hoặc tình cảm trao đi bị từ chối phụ bạc.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-01_6244606728_l.jpg'
  },
  {
    id: 37,
    slug: 'two-of-cups',
    nameEn: 'Deux de Coupe',
    nameVi: 'Deux de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: '2',
    keywordsVi: ['hòa hợp kết nối', 'tình cảm đôi lứa', 'chia sẻ thấu hiểu', 'sự phản chiếu tốt đẹp'],
    meaningUpright: 'Hai chiếc chén song hành biểu thị sự phản chiếu cảm xúc tốt đẹp và sự kết nối hài hòa sâu sắc giữa đôi bên. Khởi đầu của một tình bạn bền vững hoặc tình yêu ngọt ngào.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự bất hòa hiểu lầm phát sinh, rạn nứt kết nối tình cảm do ích kỷ thiếu chia sẻ thấu hiểu thực lòng.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-02_6244610322_l.jpg'
  },
  {
    id: 38,
    slug: 'three-of-cups',
    nameEn: 'Trois de Coupe',
    nameVi: 'Trois de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: '3',
    keywordsVi: ['ăn mừng thành quả', 'tình bạn gắn kết', 'chia sẻ niềm vui', 'sự trù phú cảm xúc'],
    meaningUpright: 'Ba chiếc cúp tụ hội biểu thị niềm vui đoàn tụ, ăn mừng cột mốc thành công và chia sẻ tình cảm ấm áp với những người bạn tri kỷ gắn kết lâu năm.',
    meaningReversed: 'Trạng thái ngược chỉ sự hoang phí tình cảm năng lượng vào tiệc tùng vô bổ, thói đố kỵ ngầm phá hỏng sự gắn kết bè phái.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-03_6244095419_l.jpg'
  },
  {
    id: 39,
    slug: 'four-of-cups',
    nameEn: 'Quatre de Coupe',
    nameVi: 'Quatre de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: '4',
    keywordsVi: ['sự chán nản tẻ nhạt', 'bão hòa cảm xúc', 'đóng kín lòng mình', 'tĩnh lặng suy ngẫm'],
    meaningUpright: 'Bốn chiếc cúp biểu thị trạng thái bão hòa cảm xúc dẫn đến chán nản tẻ nhạt, đóng kín lòng mình trước cơ hội mới. Bạn cần thời gian tĩnh lặng tự suy ngẫm hướng đi.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự bừng tỉnh thoát khỏi trạng thái trầm u uất, cởi mở đón nhận năng lượng tích cực và các mối quan hệ mới bên ngoài.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-04_6244615498_l.jpg'
  },
  {
    id: 40,
    slug: 'five-of-cups',
    nameEn: 'Cinq de Coupe',
    nameVi: 'Cinq de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: '5',
    keywordsVi: ['nuối tiếc mất mát', 'thất vọng sâu sắc', 'nỗi buồn chia ly', 'vết thương chưa lành'],
    meaningUpright: 'Cinq de Coupe biểu thị vết thương lòng đau đớn, nỗi nuối tiếc mất mát cảm xúc lớn lao trong quá khứ. Hãy nhìn nhận thực tế và trân trọng những gì tốt đẹp còn lại.',
    meaningReversed: 'Trạng thái ngược cho thấy sự chấp nhận nỗi đau để bước tiếp, bắt đầu quá trình hàn gắn trái tim tổn thương và mở lòng đón nhận hạnh phúc mới.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-05_6244100791_l.jpg'
  },
  {
    id: 41,
    slug: 'six-of-cups',
    nameEn: 'Six de Coupe',
    nameVi: 'Six de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: '6',
    keywordsVi: ['ký ức trong trẻo', 'hoài niệm tốt đẹp', 'sự quay lại cố nhân', 'hàn gắn cảm xúc'],
    meaningUpright: 'Sáu chiếc cúp mang năng lượng dịu ngọt kết nối với những kỷ niệm hoài niệm trong trẻo từ quá khứ, giúp xoa dịu những tổn thương khô cằn của cuộc sống hiện tại.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự bám víu e sợ thực tế hiện tại, chìm đắm trong vinh quang hay tiếc nuối quá khứ xa xôi một cách yếu đuối.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-06_6244103499_l.jpg'
  },
  {
    id: 42,
    slug: 'seven-of-cups',
    nameEn: 'Sept de Coupe',
    nameVi: 'Sept de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: '7',
    keywordsVi: ['nhiều ảo tưởng mê muội', 'sự lựa chọn đa đoan', 'cám dỗ ảo ảnh', 'thiếu thực tế'],
    meaningUpright: 'Bảy chiếc cúp vây quanh biểu thị quá nhiều lựa chọn mơ hồ, ảo tưởng mê muội làm lung lay ý chí thực tế. Cần tỉnh táo thanh lọc suy nghĩ trước khi quyết định hành động.',
    meaningReversed: 'Trạng thái ngược chỉ sự tỉnh ngộ gạt bỏ những ảo vọng mơ hồ, xác lập mục tiêu thực tế và lấy lại kiểm soát cuộc sống bản thân.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-07_6244106325_l.jpg'
  },
  {
    id: 43,
    slug: 'eight-of-cups',
    nameEn: 'Huit de Coupe',
    nameVi: 'Huit de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: '8',
    keywordsVi: ['ra đi lặng lẽ', 'từ bỏ tìm kiếm', 'khô cạn cảm xúc', 'dũng cảm bước tiếp'],
    meaningUpright: 'Tám chiếc cúp xếp đối xứng nhưng năng lượng đã khô cạn, biểu thị sự ra đi lặng lẽ từ bỏ hoàn cảnh cũ đã mất hết ý nghĩa để tìm kiếm những giá trị tâm linh cao đẹp hơn.',
    meaningReversed: 'Trạng thái ngược chỉ sự chần chừ e sợ từ bỏ lối mòn quen thuộc tẻ nhạt, chấp nhận sống chết mòn trong cảm xúc cạn kiệt.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-08_6244627350_l.jpg'
  },
  {
    id: 44,
    slug: 'nine-of-cups',
    nameEn: 'Neuf de Coupe',
    nameVi: 'Neuf de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: '9',
    keywordsVi: ['hài lòng tự tại', 'ước nguyện hiển lộ', 'sự viên mãn tình cảm', 'an lành'],
    meaningUpright: 'Neuf de Coupe mang ý nghĩa viên mãn tình cảm, cảm giác tự tại hài lòng tối đa với cuộc sống hiện tại. Mọi ước nguyện chân thành của bạn đều có cơ hội hiển lộ thành sự thật.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự tự mãn ích kỷ kiêu ngạo, thói nuông chiều bản ngã và lòng tham vật chất che lấp ý nghĩa tinh thần sâu sắc.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-09_6244630242_l.jpg'
  },
  {
    id: 45,
    slug: 'ten-of-cups',
    nameEn: 'Dix de Coupe',
    nameVi: 'Dix de Coupe',
    arcana: 'minor',
    suit: 'cups',
    number: '10',
    keywordsVi: ['gia đình viên mãn', 'hài hòa lâu dài', 'bình yên nội tại', 'sự kết nối hoàn hảo'],
    meaningUpright: 'Mười chiếc cúp biểu thị dòng chảy tình thương ngập tràn vương quốc nội tâm, mang lại sự hòa hợp bền vững cho gia đình và các mối quan hệ tình cảm thân thiết nhất.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự rạn nứt bất hòa ngầm trong gia đình bị che đậy dưới vỏ bọc yên bình giả tạo bên ngoài xã hội.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-10_6244115453_l.jpg'
  },
  {
    id: 46,
    slug: 'valet-de-coupe',
    nameEn: 'Valet de Coupe',
    nameVi: 'Valet Chén',
    arcana: 'minor',
    suit: 'cups',
    number: '11',
    keywordsVi: ['thông điệp tình cảm', 'trực giác trong sáng', 'tâm hồn nhạy cảm', 'rung động nghệ thuật'],
    meaningUpright: 'Valet de Coupe đại diện cho bạn trẻ mang trái tim nhạy cảm tinh tế, trực giác trong sáng và khao khát học hỏi nghệ thuật bằng tình yêu chân thành sâu sắc.',
    meaningReversed: 'Trạng thái ngược chỉ sự ủy mị ướt át quá đà, thói giận dỗi e thẹn thái quá hoặc tin tức tình cảm e ngại thất vọng cản trở.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-11-valet-de-coupe_6244118843_l.jpg'
  },
  {
    id: 47,
    slug: 'cavalier-de-coupe',
    nameEn: 'Cavalier de Coupe',
    nameVi: 'Cavalier Chén',
    arcana: 'minor',
    suit: 'cups',
    number: '12',
    keywordsVi: ['sứ giả yêu thương', 'chinh phục trái tim', 'tinh tế nghệ sĩ', 'thao túng cảm xúc'],
    meaningUpright: 'Cavalier de Coupe mang chiếc cúp đi thong thả biểu thị hành trình trao gửi tình thương, chinh phục trái tim đối phương bằng sự tinh tế ngọt ngào nghệ sĩ.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói lừa dối tráo trở trong tình cảm, thói thao túng cảm xúc tinh vi núp bóng sự ngọt ngào giả tạo.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-12-cavalier-de-coupe_6244122509_l.jpg'
  },
  {
    id: 48,
    slug: 'queen-of-cups',
    nameEn: 'Reyne de Coupe',
    nameVi: 'Reyne Chén',
    arcana: 'minor',
    suit: 'cups',
    number: '13',
    keywordsVi: ['thấu cảm sâu sắc', 'trực giác thấu suốt', 'người mẹ hiền từ', 'sự tĩnh lặng tinh thần'],
    meaningUpright: 'Reyne de Coupe là hiện thân của sự thấu cảm tuyệt đối, khả năng lắng nghe và xoa dịu những vết thương lòng cho người khác bằng trực giác tĩnh lặng tinh thần của mình.',
    meaningReversed: 'Trạng thái ngược chỉ sự phụ thuộc cảm xúc nghiêm trọng, tính khí ghen tuông cực đoan thầm kín hoặc sự tự cô lập e sợ xã hội.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-13-reyne-de-coupe_6244126359_l.jpg'
  },
  {
    id: 49,
    slug: 'knight-of-cups',
    nameEn: 'Roy de Coupe',
    nameVi: 'Roy Chén',
    arcana: 'minor',
    suit: 'cups',
    number: '14',
    keywordsVi: ['bao dung nhân ái', 'làm chủ cảm xúc', 'bình yên vững vàng', 'sự bảo hộ âm thầm'],
    meaningUpright: 'Roy de Coupe (tương đương King of Cups) ngự trị ôn hòa trên ngai vàng giữa đại dương cảm xúc. Ông đại diện cho lòng bao dung nhân ái rộng lớn và khả năng bảo hộ che chở âm thầm vững vàng.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự lạnh lùng thiếu trắc ẩn che giấu bên ngoài, thói quen đạo đức giả lợi dụng lòng tin của kẻ dưới.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-coupes-14-roy-de-coupe_6244648294_l.jpg'
  },

  // SWORDS (Épées) (50-63)
  {
    id: 50,
    slug: 'ace-of-swords',
    nameEn: 'As de l’Épée',
    nameVi: 'As de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: 'ace',
    keywordsVi: ['sự phán quyết quyết đoán', 'tư duy sáng tỏ', 'sức mạnh công lý', 'ý tưởng sắc bén'],
    meaningUpright: 'As de l’Épée mô tả thanh gươm vương miện biểu thị sức mạnh đột phá của tư duy logic. Ý tưởng sắc bén của bạn sẽ đập tan mọi nghi ngờ và ảo ảnh để hướng tới chân lý.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự lạm dụng lý trí độc đoán tàn nhẫn, suy nghĩ tiêu cực tự gây thương tổn hoặc phán đoán sai lầm tai hại.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-01_6244651352_l.jpg'
  },
  {
    id: 51,
    slug: 'two-of-swords',
    nameEn: 'Deux de l’Épée',
    nameVi: 'Deux de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: '2',
    keywordsVi: ['cân bằng lý trí', 'thỏa hiệp tạm thời', 'do dự chọn lựa', 'tĩnh lặng suy nghĩ'],
    meaningUpright: 'Hai thanh kiếm cong giao nhau biểu thị trạng thái cân bằng lực lượng tư duy. Đây là lúc tạm hoãn xung đột, thỏa hiệp tạm thời để tĩnh lặng suy nghĩ tìm giải pháp khách quan nhất.',
    meaningReversed: 'Trạng thái ngược phản ánh sự do dự kéo dài bỏ lỡ thời cơ chín muồi, hoặc sự bất hòa sâu sắc phá vỡ thế cân bằng tạm thời.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-02_6244654618_l.jpg'
  },
  {
    id: 52,
    slug: 'three-of-swords',
    nameEn: 'Trois de l’Épée',
    nameVi: 'Trois de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: '3',
    keywordsVi: ['đau đớn u sầu', 'rạn nứt tư duy', 'sự thật phũ phàng', 'chia ly đau buồn'],
    meaningUpright: 'Trois de l’Épée biểu thị nỗi u sầu đau đớn khi các ảo tưởng cảm xúc bị đâm xuyên bởi sự thật phũ phàng của lý trí. Một giai đoạn khó khăn nhưng giúp thanh lọc nhận thức.',
    meaningReversed: 'Trạng thái ngược chỉ ra việc bám víu kéo dài nỗi đau u uất quá khứ, tự dằn vặt bản thân một cách tiêu cực không lối thoát.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-03_6244138685_l.jpg'
  },
  {
    id: 53,
    slug: 'four-of-swords',
    nameEn: 'Quatre de l’Épée',
    nameVi: 'Quatre de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: '4',
    keywordsVi: ['hồi sức đình chiến', 'tĩnh dưỡng trí não', 'rút lui cần thiết', 'chuẩn bị năng lượng'],
    meaningUpright: 'Bốn thanh kiếm đối xứng biểu thị thời kỳ đình chiến hồi sức vô cùng cần thiết. Hãy tạm rút lui khỏi tranh chấp đời thường để tĩnh dưỡng trí não và nạp lại năng lượng.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự bắt đầu hành động trở lại quá vội vã khi chưa phục hồi sức khỏe, hoặc sự lười biếng né tránh thực tại cuộc sống.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-04_6244659962_l.jpg'
  },
  {
    id: 54,
    slug: 'five-of-swords',
    nameEn: 'Cinq de l’Épée',
    nameVi: 'Cinq de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: '5',
    keywordsVi: ['thua cuộc đắng cay', 'phản bội chia rẽ', 'ảo tưởng chiến thắng', 'mất mát tinh thần'],
    meaningUpright: 'Cinq de l’Épée phản ánh sự thua cuộc đắng cay do mưu cầu ích kỷ, hoặc chiến thắng giả tạo không đem lại yên bình mà chỉ gieo rắc sự oán hận phản bội xung quanh.',
    meaningReversed: 'Trạng thái ngược chỉ ra nỗi sợ hãi thất bại ngăn cản hành động quyết định, hoặc hành vi trả đũa tiêu cực làm tổn thương sâu rộng.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-05_6244144299_l.jpg'
  },
  {
    id: 55,
    slug: 'six-of-swords',
    nameEn: 'Six de l’Épée',
    nameVi: 'Six de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: '6',
    keywordsVi: ['chuyển biến tích cực', 'sáng suốt tìm lối', 'khắc phục khó khăn', 'hành trình mới'],
    meaningUpright: 'Sáu thanh kiếm đan xen hướng về tương lai biểu thị sự chuyển biến tích cực của tư duy. Khó khăn lớn nhất đang lùi lại phía sau, nhường chỗ cho giải pháp thực tế khả thi.',
    meaningReversed: 'Trạng thái ngược chỉ sự bế tắc luẩn quẩn do tư duy thiếu thực tế khách quan, hoặc việc e sợ thay đổi hoàn cảnh quen thuộc.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-06_6244147015_l.jpg'
  },
  {
    id: 56,
    slug: 'seven-of-swords',
    nameEn: 'Sept de l’Épée',
    nameVi: 'Sept de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: '7',
    keywordsVi: ['mưu tính vô vọng', 'sự lừa dối lén lút', 'thiếu trung thực', 'nguy cơ thất thoát'],
    meaningUpright: 'Sept de l’Épée chỉ ra những mưu tính lén lút thiếu trung thực nhằm lách luật đều sẽ dẫn đến kết quả vô vọng thất thoát. Đã đến lúc đối mặt thẳng thắn.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự phanh phui phơi bày các âm mưu gian dối, hoặc sự thức tỉnh nhận ra kế hoạch hiện tại bất khả thi.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-07_6244151255_l.jpg'
  },
  {
    id: 57,
    slug: 'eight-of-swords',
    nameEn: 'Huit de l’Épée',
    nameVi: 'Huit de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: '8',
    keywordsVi: ['can thiệp cản trở', 'tự trói buộc tư duy', 'do dự e sợ', 'áp lực xung quanh'],
    meaningUpright: 'Huit thanh kiếm bao quanh chỉ ra sự can thiệp cản trở từ ngoại cảnh khiến bạn do dự e sợ. Bạn đang tự trói buộc tư duy của mình trong vỏ bọc lo âu phi lý.',
    meaningReversed: 'Trạng thái ngược thể hiện việc gạt bỏ được các nhiễu loạn bên ngoài, khôi phục sự sáng suốt tự tin để giải phóng bản thân khỏi bế tắc.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-08_6244155125_l.jpg'
  },
  {
    id: 58,
    slug: 'nine-of-swords',
    nameEn: 'Neuf de l’Épée',
    nameVi: 'Neuf de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: '9',
    keywordsVi: ['lo âu tột độ', 'ác mộng dằn vặt', 'tự hủy hoại tinh thần', 'cảm giác tội lỗi'],
    meaningUpright: 'Neuf de l’Épée chỉ ra sự tự hủy hoại tinh thần tột độ do dằn vặt tội lỗi ảo tưởng mang lại. Nỗi lo âu và ác mộng bám riết lấy bạn, hãy ngừng tự hành hạ bản thân.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự chấm dứt của bóng tối sợ hãi mơ hồ, bắt đầu mở lòng đón nhận ánh sáng ý thức hồi phục tinh thần.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-09_6244676384_l.jpg'
  },
  {
    id: 59,
    slug: 'ten-of-swords',
    nameEn: 'Dix de l’Épée',
    nameVi: 'Dix de l’Épée',
    arcana: 'minor',
    suit: 'swords',
    number: '10',
    keywordsVi: ['sụp đổ triệt để', 'kết thúc đau đớn', 'chạm đáy nỗi đau', 'sự tái thiết lại'],
    meaningUpright: 'Mười thanh kiếm đan xen dày đặc biểu thị sự sụp đổ triệt để của cấu trúc tư duy cũ kỹ lỗi thời. Bạn đã chạm đáy nỗi đau đớn khó khăn nhất, chỉ còn con đường đứng dậy tái thiết lại.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự tái sinh thần kỳ từ đống tro tàn đổ nát, bắt đầu xây dựng lại cuộc sống trên nền tảng tri thức thực tế.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-10_6244680102_l.jpg'
  },
  {
    id: 60,
    slug: 'valet-de-epee',
    nameEn: 'Valet de l’Épée',
    nameVi: 'Valet Kiếm',
    arcana: 'minor',
    suit: 'swords',
    number: '11',
    keywordsVi: ['tin tức bất ngờ', 'phản biện sắc sảo', 'người canh gác chân lý', 'sự nổi loạn tinh thần'],
    meaningUpright: 'Valet de l’Épée đại diện cho bạn trẻ mang tư duy sắc sảo, dũng cảm phản biện truy tìm chân lý bất chấp mọi định kiến rào cản xã hội.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói xoi mói ngồi lê đôi mách độc hại, thói khẩu chiến gây chia rẽ hoặc sự e dè nhút nhát.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-11-valet-de-epe_6244166109_l.jpg'
  },
  {
    id: 61,
    slug: 'cavalier-de-epee',
    nameEn: 'Cavalier de l’Épée',
    nameVi: 'Cavalier Kiếm',
    arcana: 'minor',
    suit: 'swords',
    number: '12',
    keywordsVi: ['hành động quyết đoán', 'tấn công trí tuệ', 'lý trí tàn nhẫn', 'thiếu kiên nhẫn'],
    meaningUpright: 'Cavalier de l’Épée lao ngựa dũng mãnh giương kiếm biểu thị hành động lý trí quyết đoán nhanh chóng, đập tan mọi khó khăn phức tạp bằng trí tuệ sắc bén.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự nóng giận thô bạo gây tổn hại giao tiếp, thói quen hành động hồ đồ thiếu chuẩn bị chín chắn.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-12-cavalier-de-epe_6244170521_l.jpg'
  },
  {
    id: 62,
    slug: 'queen-of-swords',
    nameEn: 'Reyne de l’Épée',
    nameVi: 'Reyne Kiếm',
    arcana: 'minor',
    suit: 'swords',
    number: '13',
    keywordsVi: ['trí tuệ độc lập', 'ranh giới rõ ràng', 'phán quyết sắc bén', 'sự công minh quý phái'],
    meaningUpright: 'Reyne de l’Épée ngự trị vững vàng giữ thanh kiếm dựng đứng biểu thị trí tuệ độc lập tự chủ sâu sắc, khả năng phán đoán công minh quý phái và thiết lập ranh giới an toàn.',
    meaningReversed: 'Trạng thái ngược chỉ sự cay nghiệt lạnh lùng trong quan hệ, định kiến cá nhân sâu sắc hoặc sự u uất tự cô lập bản thân.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-13-reyne-de-epe_6244174041_l.jpg'
  },
  {
    id: 63,
    slug: 'knight-of-swords',
    nameEn: 'Roy de l’Épée',
    nameVi: 'Roy Kiếm',
    arcana: 'minor',
    suit: 'swords',
    number: '14',
    keywordsVi: ['lãnh đạo lý trí', 'luật pháp nghiêm minh', 'quyết phán quyết đoán', 'trí tuệ kiệt xuất'],
    meaningUpright: 'Roy de l’Épée (tương đương King of Swords) nắm giữ quyền lực phán quyết tối cao bằng luật pháp nghiêm minh và tư duy kiệt xuất khách quan trọn vẹn.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói bạo chúa độc tài tư tưởng, phán quyết tàn nhẫn thiếu tình thương hoặc mưu tính lừa dối cấp dưới.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-epes-14-roy-de-epe_6244178177_l.jpg'
  },

  // PENTACLES / COINS (Deniers) (64-77)
  {
    id: 64,
    slug: 'ace-of-pentacles',
    nameEn: 'As de Deniers',
    nameVi: 'As de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: 'ace',
    keywordsVi: ['hạt giống vật chất', 'cơ hội tài chính', 'thịnh vượng trần gian', 'sức khỏe tốt'],
    meaningUpright: 'As de Deniers mô tả đồng tiền vàng lớn rực rỡ mang năng lượng sung túc của đất mẹ. Khởi đầu tuyệt vời cho việc đầu tư kinh doanh, cơ hội tài chính vững bền và sức khỏe dồi dào.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự bỏ lỡ cơ hội kinh tế thiết thực, chi tiêu hoang phí thất thoát tài sản ban đầu hoặc thể trạng mệt mỏi.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-01_6244699404_l.jpg'
  },
  {
    id: 65,
    slug: 'two-of-pentacles',
    nameEn: 'Deux de Deniers',
    nameVi: 'Deux de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: '2',
    keywordsVi: ['linh hoạt thích ứng', 'cân đối dòng tiền', 'chu chuyển tài sản', 'sự thay đổi khéo léo'],
    meaningUpright: 'Deux de Deniers mô tả hai đồng xu kết nối bởi dải ruy băng xoắn biểu thị sự linh hoạt thích ứng khéo léo để giữ thăng bằng tài chính trước những biến động đời thường.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự mất cân đối tài chính do chi tiêu vượt quá thu nhập, hoặc sự hoang mang dao động trước quá nhiều áp lực dồn dập.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-02_6244703190_l.jpg'
  },
  {
    id: 66,
    slug: 'three-of-pentacles',
    nameEn: 'Trois de Deniers',
    nameVi: 'Trois de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: '3',
    keywordsVi: ['kiến thiết cấu trúc', 'tay nghề xuất sắc', 'đồng lòng xây dựng', 'thực thi vững vàng'],
    meaningUpright: 'Ba đồng xu đan xen hoa văn biểu thị quá trình thực thi vững vàng của kế hoạch xây dựng thực tế. Sự đồng lòng hợp tác chuyên môn đem lại kết quả vật chất bền vững.',
    meaningReversed: 'Trạng thái ngược chỉ sự thiếu tập trung chuyên môn dẫn đến sản phẩm kém chất lượng, hoặc mâu thuẫn nội bộ cản trở công trình.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-03_6244187495_l.jpg'
  },
  {
    id: 67,
    slug: 'four-of-pentacles',
    nameEn: 'Quatre de Deniers',
    nameVi: 'Quatre de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: '4',
    keywordsVi: ['bảo thủ tài chính', 'tích lũy an toàn', 'đề phòng rủi ro', 'sự vững chãi vật chất'],
    meaningUpright: 'Quatre de Deniers biểu thị sự tích lũy của cải an toàn tuyệt đối. Bạn giữ chặt tài sản của mình và từ chối mọi kế hoạch đầu tư mạo hiểm để bảo vệ vị thế vững chãi.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói keo kiệt bủn xỉn làm ngưng trệ dòng chảy tiền bạc, hoặc nguy cơ mất mát bất ngờ do bảo thủ cứng nhắc.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-04_6244709388_l.jpg'
  },
  {
    id: 68,
    slug: 'five-of-pentacles',
    nameEn: 'Cinq de Deniers',
    nameVi: 'Cinq de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: '5',
    keywordsVi: ['lo âu tiền bạc', 'khủng hoảng vật chất', 'cảm giác cô độc thiếu thốn', 'thất thoát nguồn lực'],
    meaningUpright: 'Cinq de Deniers phản ánh sự lo âu căng thẳng cực độ về tiền bạc vật chất. Cảm giác thiếu thốn nguồn lực và cô độc e sợ vây quanh bạn, cần bình tĩnh phục hồi.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự vượt qua giai đoạn khó khăn tài chính ngặt nghèo nhất, tìm thấy sự giúp đỡ thực tế hoặc phục hồi thể trạng.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-05_6244194121_l.jpg'
  },
  {
    id: 69,
    slug: 'six-of-pentacles',
    nameEn: 'Six de Deniers',
    nameVi: 'Six de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: '6',
    keywordsVi: ['chia sẻ hào phóng', 'sự hỗ trợ công bằng', 'dòng tài chính cân đối', 'nhận phần thưởng quả ngọt'],
    meaningUpright: 'Sáu đồng xu sắp xếp đối xứng biểu thị sự hỗ trợ công bằng và chia sẻ hào phóng tài lộc đúng người đúng thời điểm. Dòng chảy tài chính đạt thế cân đối lành mạnh.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự ban ơn hạ cố gây oán hận, thói ỷ lại lười biếng từ kẻ dưới hoặc nợ nần phát sinh ngoài kế hoạch.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-06_6244197445_l.jpg'
  },
  {
    id: 70,
    slug: 'seven-of-pentacles',
    nameEn: 'Sept de Deniers',
    nameVi: 'Sept de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: '7',
    keywordsVi: ['thất vọng thu hoạch', 'kiên nhẫn xem xét', 'sự trì trệ', 'tích lũy chậm chạp'],
    meaningUpright: 'Sept de Deniers chỉ ra sự thất vọng nhẹ do thành quả thu hoạch chậm chạp không như kỳ vọng ban đầu. Lá bài khuyên bạn kiên nhẫn xem xét điều chỉnh phương pháp.',
    meaningReversed: 'Trạng thái ngược chỉ sự nản lòng buông xuôi bỏ phí công sức gieo trồng bấy lâu, hoặc quyết định rút lui cắt lỗ thông minh kịp thời.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-07_6244201233_l.jpg'
  },
  {
    id: 71,
    slug: 'eight-of-pentacles',
    nameEn: 'Huit de Deniers',
    nameVi: 'Huit de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: '8',
    keywordsVi: ['rèn luyện tay nghề', 'chăm chỉ tỉ mỉ', 'tích lũy kiên trì', 'sự thận trọng thực tế'],
    meaningUpright: 'Huit de Deniers biểu thị tinh thần làm việc chăm chỉ tỉ mỉ, kiên trì tích lũy của cải từng bước một. Bạn đang rèn luyện kỹ năng tay nghề đạt độ chín muồi.',
    meaningReversed: 'Trạng thái ngược chỉ thói làm việc cẩu thả đốt cháy giai đoạn gây hư hỏng sản phẩm, hoặc thói lười biếng bê trễ công việc được giao.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-08_6244723466_l.jpg'
  },
  {
    id: 72,
    slug: 'nine-of-pentacles',
    nameEn: 'Neuf de Deniers',
    nameVi: 'Neuf de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: '9',
    keywordsVi: ['thành quả dồi dào', 'tự do tài chính', 'hưởng thụ cuộc sống', 'thịnh vượng quý phái'],
    meaningUpright: 'Chín đồng xu xếp đối xứng biểu thị thành quả dồi dào gặt hái được sau nỗ lực bền bỉ. Bạn được tự do tài chính và tự tại hưởng thụ cuộc sống thịnh vượng quý phái.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói nuông chiều bản thân quá mức gây hao tán tài sản, hoặc sự hoang phí tiền của vào việc phô trương danh hão.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-09_6244726672_l.jpg'
  },
  {
    id: 73,
    slug: 'ten-of-pentacles',
    nameEn: 'Dix de Deniers',
    nameVi: 'Dix de Deniers',
    arcana: 'minor',
    suit: 'pentacles',
    number: '10',
    keywordsVi: ['di sản gia đình', 'thành tựu vững chắc', 'giàu có vĩnh cửu', 'thịnh vượng toàn diện'],
    meaningUpright: 'Dix de Deniers biểu thị đỉnh cao thịnh vượng toàn diện vật chất thế gian, mang ý nghĩa thiết lập di sản gia đình vững chắc lâu đời và sự bảo hộ tiền của bền vững.',
    meaningReversed: 'Trạng thái ngược cảnh báo tranh chấp quyền thừa kế tài sản gay gắt trong gia đình, đầu tư mạo hiểm dẫn đến nguy cơ vỡ nợ lớn.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-10_6244211873_l.jpg'
  },
  {
    id: 74,
    slug: 'valet-de-deniers',
    nameEn: 'Valet de Deniers',
    nameVi: 'Valet Xu',
    arcana: 'minor',
    suit: 'pentacles',
    number: '11',
    keywordsVi: ['cơ hội kinh doanh', 'học hỏi thực tế', 'chăm chỉ cẩn trọng', 'khởi sự tài chính'],
    meaningUpright: 'Valet de Deniers đại diện cho người trẻ chăm chỉ cẩn trọng, khao khát học hỏi chuyên môn thực tế và tìm kiếm cơ hội khởi nghiệp tài chính vững vàng.',
    meaningReversed: 'Trạng thái ngược chỉ thói lười biếng thụ động e ngại khó khăn thực tế, sự thiếu tầm nhìn kinh doanh hoặc dự án bị đình trệ.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-11-valet-de-deniers_6244734282_l.jpg'
  },
  {
    id: 75,
    slug: 'cavaliers-de-deniers',
    nameEn: 'Cavaliers de Deniers',
    nameVi: 'Cavaliers Xu',
    arcana: 'minor',
    suit: 'pentacles',
    number: '12',
    keywordsVi: ['bền bỉ kiên trì', 'làm việc khoa học', 'chậm rãi chắc chắn', 'trung thành tận tụy'],
    meaningUpright: 'Cavaliers de Deniers biểu thị sự kiên trì bền bỉ vượt bậc, thực hiện công việc chậm rãi chắc chắn theo phương pháp khoa học mang lại hiệu quả cao nhất.',
    meaningReversed: 'Trạng thái ngược chỉ sự cứng đầu bướng bỉnh lỗi thời, thói lười biếng không chịu đổi mới tư duy hoặc xu hướng quá thực dụng.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-12-cavaliers-de-deniers_6244738028_l.jpg'
  },
  {
    id: 76,
    slug: 'queen-of-pentacles',
    nameEn: 'Reyne de Deniers',
    nameVi: 'Reyne Xu',
    arcana: 'minor',
    suit: 'pentacles',
    number: '13',
    keywordsVi: ['nuôi dưỡng trù phú', 'kinh nghiệm thực tế', 'bình yên vững chãi', 'quản lý xuất sắc'],
    meaningUpright: 'Reyne de Deniers biểu thị sự bao dung nuôi dưỡng trù phú, khả năng quản lý chi tiêu thực tế xuất sắc bảo vệ nền tảng tài chính bình yên vững chãi.',
    meaningReversed: 'Trạng thái ngược chỉ sự hoang mang e sợ mất an toàn vật chất dẫn đến keo kiệt bủn xỉn quá mức, hoặc thói bao bọc quá đà có hại.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-13-reyne-de-deniers_6244741116_l.jpg'
  },
  {
    id: 77,
    slug: 'knight-of-pentacles',
    nameEn: 'Roy de Deniers',
    nameVi: 'Roy Xu',
    arcana: 'minor',
    suit: 'pentacles',
    number: '14',
    keywordsVi: ['thành tựu rực rỡ', 'lãnh đạo thực tiễn', 'gia sản vững bền', 'sự kiên định thịnh vượng'],
    meaningUpright: 'Roy de Deniers (tương đương King of Pentacles) nắm giữ gia sản to lớn nhờ kiên định lãnh đạo thực tiễn lâu năm mang lại sự thịnh vượng rực rỡ.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói thực dụng lạnh lùng thờ ơ nhân tình, đầu tư bảo thủ kiêu ngạo cản trở dòng chảy phát triển chung.',
    imagePath: '/Tarot_de_Marseille/marseille-arcanes-mineurs-deniers-14-roy-de-deniers_6244227245_l.jpg'
  }
];

export function getCardById(id: number): TarotCard | undefined {
  return marseilleCards.find((card) => card.id === id);
}

export function getCardBySlug(slug: string): TarotCard | undefined {
  return marseilleCards.find((card) => card.slug === slug);
}
