import { TarotCard } from './cards-data';

export const thothCards: TarotCard[] = [
  // MAJOR ARCANA (0-21)
  {
    id: 0,
    slug: 'the-fool',
    nameEn: 'The Fool',
    nameVi: 'Kẻ Khờ',
    arcana: 'major',
    number: '0',
    keywordsVi: ['khởi đầu mới', 'tự do hoang dại', 'năng lượng vô hạn', 'tiềm năng thần thánh', 'sự điên rồ linh thiêng'],
    meaningUpright: 'Kẻ Khờ trong bộ Thoth đại diện cho khoảng không vô tận trước khi sáng thế, hiện thân của vị thần Dionysus với năng lượng sống tuôn trào tự do, phóng khoáng. Lá bài khuyến khích bạn bước đi bằng niềm tin tuyệt đối vào tiếng gọi của linh hồn, vượt qua mọi nỗi sợ hãi và rào cản lý trí thông thường.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự hoang phí năng lượng vô bổ, sự bốc đồng, điên rồ thiếu kiểm soát. Bạn đang từ chối cơ hội phát triển hoặc bước đi một cách mù quáng, bỏ qua tiếng nói của trực giác và cảnh báo thực tế.',
    imagePath: '/Thoth_Tarot/thoth-trumps-00-the-fool_6242948151_l.jpg'
  },
  {
    id: 1,
    slug: 'the-magus',
    nameEn: 'The Magus',
    nameVi: 'Pháp Sư',
    arcana: 'major',
    number: '1',
    keywordsVi: ['sự giao tiếp', 'chủ động', 'thao tác năng lượng', 'khả năng thích ứng', 'sáng tạo'],
    meaningUpright: 'The Magus đại diện cho thần Mercury (Hermes) - sứ giả của các vị thần, vị thần của ngôn từ, phép thuật và giao thương. Người nắm giữ quyền năng biểu hiện ý chí tâm linh thành hiện thực vật chất thông qua sự tập trung ý chí và làm chủ các công cụ ma thuật.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự xảo quyệt, thao túng thông tin, lừa lọc hoặc lạm dụng quyền lực trí tuệ. Bạn có thể đang gặp khó khăn trong việc tập trung ý chí hoặc đang cố áp đặt cái tôi cá nhân lên dòng chảy tự nhiên.',
    imagePath: '/Thoth_Tarot/thoth-trumps-01a-the-magus_6242951139_l.jpg'
  },
  {
    id: 2,
    slug: 'the-priestess',
    nameEn: 'The Priestess',
    nameVi: 'Nữ Tư Tế',
    arcana: 'major',
    number: '2',
    keywordsVi: ['trực giác', 'bí ẩn', 'kết nối tâm linh', 'sự thuần khiết', 'tiềm thức'],
    meaningUpright: 'Nữ Tư Tế của Thoth được bao phủ bởi tấm màng ánh sáng của nữ thần Isis. Nàng là cầu nối trực tiếp đến thế giới nội tâm và nguồn tri thức vũ trụ nguyên sơ. Lá bài kêu gọi bạn hãy tĩnh lặng, lắng nghe trực giác sâu thẳm và tin tưởng vào những điều chưa hiển lộ.',
    meaningReversed: 'Trạng thái ngược cho thấy sự xa rời thực tế, trốn tránh cuộc sống hoặc phớt lờ trực giác. Có thể bạn đang bị cuốn vào những bí mật đen tối, sự hoang mang hoặc phụ thuộc cảm xúc vào người khác.',
    imagePath: '/Thoth_Tarot/thoth-trumps-02-the-priestess_6243477936_l.jpg'
  },
  {
    id: 3,
    slug: 'the-empress',
    nameEn: 'The Empress',
    nameVi: 'Nữ Hoàng',
    arcana: 'major',
    number: '3',
    keywordsVi: ['tình yêu vô điều kiện', 'sinh sôi nảy nở', 'sự trù phú', 'nghệ thuật', 'nữ tính'],
    meaningUpright: 'The Empress đại diện cho nữ thần tình yêu và sắc đẹp Aphrodite. Đây là biểu tượng của thiên nhiên giàu có, trù phú, sự nuôi dưỡng và sinh sản. Năng lượng của lá bài mang đến sự thịnh vượng, khơi nguồn sáng tạo nghệ thuật và sự ấm áp trong các mối quan hệ.',
    meaningReversed: 'Trạng thái ngược thể hiện sự kiểm soát thái quá, tính chiếm hữu cao hoặc sự trì trệ trong sáng tạo. Bạn có thể đang bỏ bê bản thân hoặc gặp trục trặc trong việc nuôi dưỡng cảm xúc, thiếu đi sự bao dung.',
    imagePath: '/Thoth_Tarot/thoth-trumps-03-the-empress_6242964111_l.jpg'
  },
  {
    id: 4,
    slug: 'the-emperor',
    nameEn: 'The Emperor',
    nameVi: 'Hoàng Đế',
    arcana: 'major',
    number: '4',
    keywordsVi: ['trật tự', 'quyền lực', 'tính kiến thiết', 'lãnh đạo', 'nguyên tắc'],
    meaningUpright: 'Hoàng Đế trong bộ Thoth đại diện cho quyền lực thế gian đầy uy nghiêm, gắn liền với biểu tượng cung Bạch Dương sáng sủa và năng động. Ông thiết lập trật tự, luật lệ và cấu trúc để bảo vệ và phát triển vương quốc. Lá bài khuyến khích sự tự chủ, kỷ luật và hành động quyết đoán.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói độc tài, cứng nhắc, thích kiểm soát người khác hoặc ngược lại là sự thiếu bản lĩnh, nhu nhược, không có khả năng thiết lập trật tự trong cuộc sống cá nhân.',
    imagePath: '/Thoth_Tarot/thoth-trumps-04-the-emperor_6242967627_l.jpg'
  },
  {
    id: 5,
    slug: 'the-hierophant',
    nameEn: 'The Hierophant',
    nameVi: 'Đại Giáo Hoàng',
    arcana: 'major',
    number: '5',
    keywordsVi: ['truyền thống', 'tri thức tâm linh', 'nghi lễ', 'sự khai tâm', 'niềm tin'],
    meaningUpright: 'The Hierophant đại diện cho vị thầy tâm linh, người nắm giữ chìa khóa khai mở các bí tích cổ xưa. Với biểu tượng Kim Ngưu vững chãi, lá bài hướng tới việc học hỏi sâu sắc, tôn trọng các giá trị truyền thống, tìm kiếm ý nghĩa triết học sâu xa và sự hòa hợp tâm hồn.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự giáo điều, bảo thủ, chống đối mù quáng các quy chuẩn xã hội hoặc sự lừa dối từ các thế lực nhân danh đức tin. Đã đến lúc bạn cần tự đi tìm chân lý riêng thay vì tuân phục giáo điều.',
    imagePath: '/Thoth_Tarot/thoth-trumps-05-the-hierophant_6242971545_l.jpg'
  },
  {
    id: 6,
    slug: 'the-lovers',
    nameEn: 'The Lovers',
    nameVi: 'Đôi Tình Nhân',
    arcana: 'major',
    number: '6',
    keywordsVi: ['sự hợp nhất', 'lựa chọn lớn', 'giả kim thuật', 'phản chiếu', 'sự cân bằng'],
    meaningUpright: 'The Lovers trong Thoth mô tả Lễ cưới Hóa học (Alchemical Marriage) giữa Vua Đỏ và Nữ Hoàng Trắng, biểu thị sự hợp nhất giữa các mặt đối lập (nam tính - nữ tính, lý trí - trực giác). Lá bài nói về những lựa chọn có tầm ảnh hưởng lớn đến cuộc đời và sự cân bằng nội tâm.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự bất hòa, xung đột nội tâm hoặc mất cân bằng trong mối quan hệ. Có thể bạn đang né tránh đưa ra quyết định khó khăn hoặc đưa ra lựa chọn sai lầm do sự chia rẽ trong suy nghĩ.',
    imagePath: '/Thoth_Tarot/thoth-trumps-06-the-lovers_6242975111_l.jpg'
  },
  {
    id: 7,
    slug: 'the-chariot',
    nameEn: 'The Chariot',
    nameVi: 'Cỗ Xe Chiến Thắng',
    arcana: 'major',
    number: '7',
    keywordsVi: ['ý chí sắt đá', 'sự tập trung', 'vượt qua chướng ngại', 'bảo vệ', 'chiến thắng'],
    meaningUpright: 'The Chariot mang hình ảnh chiến sĩ cầm chiếc Chén Thánh được bảo vệ bởi bộ giáp hổ phách vững chắc. Lá bài đại diện cho việc làm chủ cảm xúc thông qua ý chí mạnh mẽ để tiến lên phía trước. Chiến thắng đến từ sự tập trung cao độ và kỷ luật nội tâm tự thân.',
    meaningReversed: 'Trạng thái ngược phản ánh sự mất phương hướng, thiếu kiểm soát, hoặc ý chí bị lung lay trước áp lực bên ngoài. Bạn có thể đang gặp phải rào cản lớn hoặc hành động quá hung hăng dẫn đến thất bại.',
    imagePath: '/Thoth_Tarot/thoth-trumps-07-the-chariot_6242978247_l.jpg'
  },
  {
    id: 8,
    slug: 'adjustment',
    nameEn: 'Adjustment',
    nameVi: 'Sự Cân Bằng',
    arcana: 'major',
    number: '8',
    keywordsVi: ['công lý', 'luật nhân quả', 'sự điều chỉnh', 'cân bằng động', 'chân lý'],
    meaningUpright: 'Lá bài Adjustment (tương đương Justice ở RWS) trong Thoth mang tính chất của cung Thiên Bình. Nữ thần Maat đứng trên mũi chân, giữ chiếc cân thăng bằng tuyệt đối nhờ thanh gươm trí tuệ. Lá bài chỉ ra sự điều chỉnh cần thiết trong cuộc sống để tìm lại thế cân bằng, đối diện với nghiệp quả một cách trung thực.',
    meaningReversed: 'Trạng thái ngược biểu thị sự bất công, định kiến hoặc mất cân bằng nghiêm trọng. Bạn có thể đang trốn tránh trách nhiệm pháp lý hoặc đạo đức, hay cố tình phán xét phiến diện một tình huống.',
    imagePath: '/Thoth_Tarot/thoth-trumps-08-adjustment_6242981713_l.jpg'
  },
  {
    id: 9,
    slug: 'the-hermit',
    nameEn: 'The Hermit',
    nameVi: 'Ẩn Sĩ',
    arcana: 'major',
    number: '9',
    keywordsVi: ['hướng nội', 'sự cô độc', 'ánh sáng nội tâm', 'tìm kiếm chân lý', 'người dẫn đường'],
    meaningUpright: 'Ẩn Sĩ của Thoth đại diện cho thần Hermes vác ngọn đèn chứa ngọn lửa thần thánh ẩn sâu dưới lòng đất. Lá bài khuyến khích bạn tạm rút lui khỏi thế giới ồn ào bên ngoài để tự suy ngẫm, kết nối với nguồn tri thức tâm linh tự thân và thắp sáng con đường riêng của mình.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự cô lập cực đoan, cô độc bệnh lý hoặc sự từ chối tiếp thu lời khuyên thông thái. Có thể bạn đang tự nhốt mình trong thế giới ảo tưởng hoặc lo sợ việc đối mặt với thực tế xã hội.',
    imagePath: '/Thoth_Tarot/thoth-trumps-09-the-hermit_6242984839_l.jpg'
  },
  {
    id: 10,
    slug: 'fortune',
    nameEn: 'Fortune',
    nameVi: 'Vòng Quay Vận Mệnh',
    arcana: 'major',
    number: '10',
    keywordsVi: ['sự thay đổi', 'vận may', 'chu kỳ cuộc sống', 'cơ hội mới', 'luật vũ trụ'],
    meaningUpright: 'Lá bài Fortune miêu tả bánh xe vận mệnh xoay vần với sự hiện diện của Sphinx, Hermanubis và Typhon. Lá bài nhắc nhở chúng ta về các chu kỳ lên xuống không ngừng của số phận. Một sự thay đổi lớn đang đến, hãy cởi mở đón nhận và nương theo dòng chảy năng lượng của vũ trụ.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự kháng cự đối với thay đổi cần thiết hoặc chuỗi vận xui do các hành động thiếu sáng suốt trong quá khứ mang lại. Hãy bình tĩnh học bài học từ nghịch cảnh trước khi bánh xe xoay vòng mới.',
    imagePath: '/Thoth_Tarot/thoth-trumps-10-fortune_6242988207_l.jpg'
  },
  {
    id: 11,
    slug: 'lust',
    nameEn: 'Lust',
    nameVi: 'Đam Mê mãnh liệt',
    arcana: 'major',
    number: '11',
    keywordsVi: ['năng lượng sống', 'hoang dã', 'sức mạnh sáng tạo', 'lòng dũng cảm', 'sự cuồng nhiệt'],
    meaningUpright: 'Lust (tương đương Strength của RWS) trong Thoth mang năng lượng rực lửa của cung Sư Tử. Hình ảnh người phụ nữ cưỡi trên lưng con thú nhiều đầu đại diện cho việc tích hợp bản năng hoang dã làm một nguồn sức mạnh sáng tạo thần thánh, thay vì chế ngự hay đè nén nó. Hãy sống trọn vẹn đam mê.',
    meaningReversed: 'Trạng thái ngược thể hiện sự cạn kiệt năng lượng sống, cảm giác bất lực hoặc ngược lại là việc buông thả bản năng thái quá, thói bạo lực và sự cuồng vọng không kiểm soát phá hủy bản thân.',
    imagePath: '/Thoth_Tarot/thoth-trumps-11-lust_6243508938_l.jpg'
  },
  {
    id: 12,
    slug: 'the-hanged-man',
    nameEn: 'The Hanged Man',
    nameVi: 'Người Treo ngược',
    arcana: 'major',
    number: '12',
    keywordsVi: ['hiến tế', 'buông bỏ cái tôi', 'góc nhìn mới', 'sự trì hoãn', 'khai sáng'],
    meaningUpright: 'Người Treo trong Thoth đại diện cho sự hiến tế cái tôi cá nhân nhỏ bé để đạt được nhận thức tâm linh cao hơn. Bị treo ngược trên cột sống hướng xuống đất, lá bài chỉ ra trạng thái tĩnh lặng bắt buộc để thanh lọc tâm trí, học cách đầu hàng trước dòng chảy số phận.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự hy sinh vô ích vì những lý do sai lầm, thói quen đóng vai nạn nhân hoặc sự trì hoãn cứng nhắc không dám hành động. Bạn đang níu kéo những thứ đã lỗi thời.',
    imagePath: '/Thoth_Tarot/thoth-trumps-12-the-hanged-man_6243511850_l.jpg'
  },
  {
    id: 13,
    slug: 'death',
    nameEn: 'Death',
    nameVi: 'Cái Chết',
    arcana: 'major',
    number: '13',
    keywordsVi: ['sự chuyển hóa', 'tái sinh', 'kết thúc chu kỳ', 'giải phóng', 'cắt bỏ'],
    meaningUpright: 'Cái Chết của Thoth mang biểu tượng con bọ cạp, con rắn và đại bàng (các dạng chuyển hóa của cung Bọ Cạp). Bộ xương nhảy múa dưới đáy sâu gieo mầm cho sự sống mới. Lá bài báo hiệu sự kết thúc triệt để của một giai đoạn để mở đường cho sự tái sinh huy hoàng hơn.',
    meaningReversed: 'Trạng thái ngược cho thấy sự sợ hãi thay đổi, níu kéo quá khứ một cách vô vọng hoặc trạng thái trì trệ, không dám đối mặt với sự kết thúc cần thiết để bắt đầu lại.',
    imagePath: '/Thoth_Tarot/thoth-trumps-13-death_6242997227_l.jpg'
  },
  {
    id: 14,
    slug: 'art',
    nameEn: 'Art',
    nameVi: 'Nghệ Thuật Giả Kim',
    arcana: 'major',
    number: '14',
    keywordsVi: ['dung hòa', 'sự hòa trộn', 'giả kim thuật', 'sáng tạo nghệ thuật', 'sự hòa hợp'],
    meaningUpright: 'Art (tương đương Temperance ở RWS) trong Thoth là đỉnh cao của quá trình giả kim thuật vĩ đại. Nữ thần lưỡng tính hòa trộn Vua Đỏ và Nữ Hoàng Trắng vào chiếc vạc thần để tạo ra vàng ròng linh hồn. Lá bài là thông điệp của sự dung hòa, sáng tạo và biến đổi nghịch cảnh thành kiệt tác.',
    meaningReversed: 'Trạng thái ngược phản ánh sự xung đột giữa các yếu tố đối nghịch, mất cân đối năng lượng hoặc sự nóng vội phá hỏng tiến trình sáng tạo tự nhiên. Bạn cần tìm lại sự hòa hợp từ bên trong.',
    imagePath: '/Thoth_Tarot/thoth-trumps-14-art_6243517528_l.jpg'
  },
  {
    id: 15,
    slug: 'the-devil',
    nameEn: 'The Devil',
    nameVi: 'Ác Quỷ',
    arcana: 'major',
    number: '15',
    keywordsVi: ['vật chất', 'sự trói buộc', 'hài hước đen', 'bản ngã sâu kín', 'phóng túng'],
    meaningUpright: 'The Devil trong Thoth mang tính chất cung Ma Kết dưới hình tượng thần Pan hoang dã của thiên nhiên. Không chỉ là sự trói buộc, lá bài còn mang thông điệp về tiếng cười châm biếm đập tan những ảo tưởng tự phụ của cái tôi, đối diện với những góc tối sâu kín nhất của bản thân để tìm tự do thực sự.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự nghiện ngập vật chất, sa đọa cảm xúc, thói thao túng tiêu cực hoặc ngược lại là nỗi sợ hãi trước những bản năng tự nhiên lành mạnh của chính mình.',
    imagePath: '/Thoth_Tarot/thoth-trumps-15-the-devil_6243003301_l.jpg'
  },
  {
    id: 16,
    slug: 'the-tower',
    nameEn: 'The Tower',
    nameVi: 'Tòa Tháp đổ',
    arcana: 'major',
    number: '16',
    keywordsVi: ['sự đổ vỡ đột ngột', 'phá hủy ảo tưởng', 'giải phóng năng lượng', 'cơn thịnh nộ', 'tự do mới'],
    meaningUpright: 'The Tower của Thoth được cai quản bởi thần chiến tranh Mars với con mắt hủy diệt rực lửa phá tan tòa tháp kiêu hãnh của loài người. Đây là sự sụp đổ đột ngột nhưng vô cùng cần thiết của những niềm tin sai lầm, những cấu trúc giả tạo để giải phóng năng lượng bị giam cầm lâu nay.',
    meaningReversed: 'Trạng thái ngược chỉ ra một cuộc khủng hoảng kéo dài, nỗi sợ hãi sụp đổ khiến bạn cố bám víu vào cấu trúc độc hại, hoặc sự tàn phá ngầm âm ỉ gây tổn thương nghiêm trọng bên trong.',
    imagePath: '/Thoth_Tarot/thoth-trumps-16-the-tower_6243006077_l.jpg'
  },
  {
    id: 17,
    slug: 'the-star',
    nameEn: 'The Star',
    nameVi: 'Ngôi Sao hy vọng',
    arcana: 'major',
    number: '17',
    keywordsVi: ['niềm tin', 'thanh lọc', 'cảm hứng vũ trụ', 'sự tươi mới', 'hi vọng'],
    meaningUpright: 'The Star mô tả nữ thần bầu trời Nuit rót dòng nước sự sống từ hai chiếc bình vàng và bạc xuống đất và biển. Lá bài mang đến sự thanh lọc sâu sắc, cảm hứng sáng tạo dồi dào và niềm hy vọng ngập tràn sau giông bão. Hãy tin tưởng vào tương lai rạng rỡ phía trước.',
    meaningReversed: 'Trạng thái ngược thể hiện sự mất niềm tin, cảm giác thất vọng tràn trề, sự cô độc hoặc cạn kiệt nguồn cảm hứng sáng tạo. Bạn đang nhìn nhận tình huống của mình một cách quá u tối.',
    imagePath: '/Thoth_Tarot/thoth-trumps-17-the-star_6243526484_l.jpg'
  },
  {
    id: 18,
    slug: 'the-moon',
    nameEn: 'The Moon',
    nameVi: 'Mặt Trăng ảo ảnh',
    arcana: 'major',
    number: '18',
    keywordsVi: ['tiềm thức', 'nỗi sợ mơ hồ', 'ảo giác', 'sự chuyển giao', 'bản năng gốc'],
    meaningUpright: 'The Moon dẫn dắt ta vào bóng tối sâu thẳm của tiềm thức thông qua cảnh cổng Anubis canh giữ. Đây là hành trình đối mặt với những nỗi sợ hãi nguyên sơ nhất, những giấc mơ kỳ lạ và ảo ảnh lừa dối. Lá bài khuyên bạn cẩn trọng trong bóng tối, tin vào bản năng của mình.',
    meaningReversed: 'Trạng thái ngược cho thấy sự xua tan ảo tưởng, tìm lại sự rõ ràng trong tâm trí hoặc vượt qua được cơn khủng hoảng tâm lý kéo dài. Tuy nhiên, nó cũng cảnh báo sự lừa dối tinh vi từ người khác.',
    imagePath: '/Thoth_Tarot/thoth-trumps-18-the-moon_6243011861_l.jpg'
  },
  {
    id: 19,
    slug: 'the-sun',
    nameEn: 'The Sun',
    nameVi: 'Mặt Trời vinh quang',
    arcana: 'major',
    number: '19',
    keywordsVi: ['sự sống', 'thành công', 'sự tự do', 'sáng tỏ', 'niềm vui thuần khiết'],
    meaningUpright: 'The Sun chiếu rọi ánh sáng rực rỡ mang nguồn sinh khí bất tận nuôi dưỡng vạn vật. Hình ảnh những đứa trẻ nhảy múa dưới ánh mặt trời đại diện cho niềm vui nguyên sơ, sự sáng tỏ tuyệt đối trong tư duy và thành công vang dội trong mọi khía cạnh đời sống.',
    meaningReversed: 'Trạng thái ngược biểu thị sự kiêu ngạo, tự mãn thái quá hoặc năng lượng bị suy giảm nhẹ. Đôi khi nó chỉ ra sự thành công bị trì hoãn hoặc cảm giác hạnh phúc chưa thực sự trọn vẹn.',
    imagePath: '/Thoth_Tarot/thoth-trumps-19-the-sun_6243532642_l.jpg'
  },
  {
    id: 20,
    slug: 'the-aeon',
    nameEn: 'The Aeon',
    nameVi: 'Kỷ Nguyên Mới',
    arcana: 'major',
    number: '20',
    keywordsVi: ['thức tỉnh', 'bước chuyển thời đại', 'tầm nhìn vĩ mô', 'sự tái sinh lớn', 'luật mới'],
    meaningUpright: 'The Aeon (tương đương Judgement ở RWS) mô tả sự ra đời của Kỷ nguyên mới Horus dưới sự giám hộ của Nuit và Hadit. Lá bài chỉ ra sự thức tỉnh nhận thức mang tầm vĩ mô, giải phóng khỏi các xiềng xích tư duy cũ kỹ của quá khứ để bước vào kỷ nguyên tự do cá nhân.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự nuối tiếc quá khứ, từ chối sự thức tỉnh tự nhiên của linh hồn hoặc việc cố chấp hành động theo những giáo điều cũ đã không còn giá trị trong kỷ nguyên mới.',
    imagePath: '/Thoth_Tarot/thoth-trumps-20-the-aeon_6243018665_l.jpg'
  },
  {
    id: 21,
    slug: 'the-universe',
    nameEn: 'The Universe',
    nameVi: 'Vũ Trụ hoàn mỹ',
    arcana: 'major',
    number: '21',
    keywordsVi: ['hoàn thành vẹn tròn', 'sự giải thoát', 'hòa nhập vũ trụ', 'thành tựu tối thượng', 'kết thúc mỹ mãn'],
    meaningUpright: 'The Universe (tương đương The World ở RWS) đại diện cho bước cuối cùng của Đại Công Trình tâm linh. Vũ công nữ thần nhảy múa trong vòng tròn vạn vật, nắm giữ chiếc khóa vạn năng. Lá bài là biểu tượng của sự hoàn thành vẹn tròn, tự do tuyệt đối và sự hòa nhập hoàn mỹ.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự trì trệ ở những bước cuối cùng của công việc, cảm giác thiếu trọn vẹn mặc dù đã đạt được mục tiêu, hoặc sự chần chừ không dám buông tay để bước sang trang mới.',
    imagePath: '/Thoth_Tarot/thoth-trumps-21-the-universe_6243021703_l.jpg'
  },

  // MINOR ARCANA (22-77)
  // WANDS (22-35)
  {
    id: 22,
    slug: 'ace-of-wands',
    nameEn: 'Ace of Wands',
    nameVi: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 'ace',
    keywordsVi: ['ngọn lửa khởi nguyên', 'ý chí thuần khiết', 'cảm hứng rực cháy', 'sức mạnh sơ khởi'],
    meaningUpright: 'Lá bài Ace of Wands của Thoth mang hình tượng Ngọn Lửa Bản Nguyên rực cháy, tượng trưng cho tia sáng ý chí đầu tiên giáng thế. Đây là nguồn năng lượng sáng tạo, động lực hành động mạnh mẽ và sự nhiệt huyết dâng tràn giúp bạn khởi sự bất kỳ kế hoạch nào.',
    meaningReversed: 'Trạng thái ngược phản ánh sự cạn kiệt năng lượng sáng tạo, nhiệt huyết bị dập tắt đột ngột hoặc ý chí bộc phát thiếu định hướng gây lãng phí tài nguyên.',
    imagePath: '/Thoth_Tarot/thoth-wands-01-ace_6243024841_l.jpg'
  },
  {
    id: 23,
    slug: 'two-of-wands',
    nameEn: 'Two of Wands (Dominion)',
    nameVi: 'Two of Wands (Quyền Lực)',
    arcana: 'minor',
    suit: 'wands',
    number: '2',
    keywordsVi: ['quyền thống trị', 'ý chí xác lập', 'sự chủ động', 'định hình hướng đi'],
    meaningUpright: 'Two of Wands mang tựa đề "Dominion" (Quyền Lực). Ý chí ban đầu đã được định hình và củng cố vững chắc. Bạn hoàn toàn làm chủ tình thế và sẵn sàng thiết lập tầm ảnh hưởng của mình lên dự án hoặc cuộc sống hiện tại.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự chuyên quyền, áp đặt ý chí thô bạo lên người khác, hoặc sự do dự, thiếu quyết đoán làm tuột mất quyền làm chủ tình huống.',
    imagePath: '/Thoth_Tarot/thoth-wands-02-dominion_6243028207_l.jpg'
  },
  {
    id: 24,
    slug: 'three-of-wands',
    nameEn: 'Three of Wands (Virtue)',
    nameVi: 'Three of Wands (Phẩm Hạnh)',
    arcana: 'minor',
    suit: 'wands',
    number: '3',
    keywordsVi: ['sự chân thành', 'hợp tác phát triển', 'tầm nhìn rộng', 'phẩm chất vững vàng'],
    meaningUpright: 'Three of Wands mang tựa đề "Virtue" (Phẩm Hạnh). Ý chí hành động được đặt trên nền tảng đạo đức chân chính và sự chân thành. Kế hoạch của bạn đang bắt đầu sinh hoa kết quả, mở ra những triển vọng hợp tác tốt đẹp lâu dài.',
    meaningReversed: 'Trạng thái ngược cho thấy sự kiêu căng dẫn đến sai lầm, hoặc kế hoạch bị chững lại do sự bất đồng ý kiến, thiếu đi tính trung thực giữa các bên tham gia.',
    imagePath: '/Thoth_Tarot/thoth-wands-03-virtue_6243031433_l.jpg'
  },
  {
    id: 25,
    slug: 'four-of-wands',
    nameEn: 'Four of Wands (Completion)',
    nameVi: 'Four of Wands (Hoàn Thành)',
    arcana: 'minor',
    suit: 'wands',
    number: '4',
    keywordsVi: ['hoàn thiện cấu trúc', 'sự vững chãi', 'ăn mừng thành quả', 'sự hài hòa'],
    meaningUpright: 'Four of Wands mang tựa đề "Completion" (Hoàn Thành). Cấu trúc của dự án đã được định hình một cách hài hòa và vững chãi nhất. Giai đoạn khó khăn nhất đã qua, đây là lúc tận hưởng cảm giác an toàn và ăn mừng thành quả bước đầu.',
    meaningReversed: 'Trạng thái ngược ám chỉ sự ổn định giả tạo, cấu trúc bên trong bắt đầu xuất hiện những vết rạn nứt do thiếu sự chăm chút tỉ mỉ từ ban đầu.',
    imagePath: '/Thoth_Tarot/thoth-wands-04-completion_6243552684_l.jpg'
  },
  {
    id: 26,
    slug: 'five-of-wands',
    nameEn: 'Five of Wands (Strife)',
    nameVi: 'Five of Wands (Xung Đột)',
    arcana: 'minor',
    suit: 'wands',
    number: '5',
    keywordsVi: ['sự đấu tranh', 'áp lực cạnh tranh', 'mâu thuẫn ý chí', 'năng lượng hỗn loạn'],
    meaningUpright: 'Five of Wands mang tựa đề "Strife" (Xung Đột). Năng lượng lửa bùng phát mạnh mẽ tạo ra sự cọ xát và cạnh tranh gay gắt. Đây là bài test bản lĩnh thách thức ý chí chiến đấu của bạn trước áp lực ngoại cảnh.',
    meaningReversed: 'Trạng thái ngược thể hiện việc trốn tránh xung đột cần thiết dẫn đến bức bối nội tâm, hoặc sự tranh chấp dai dẳng, kiệt quệ năng lượng vô nghĩa.',
    imagePath: '/Thoth_Tarot/thoth-wands-05-strife_6243038307_l.jpg'
  },
  {
    id: 27,
    slug: 'six-of-wands',
    nameEn: 'Six of Wands (Victory)',
    nameVi: 'Six of Wands (Chiến Thắng)',
    arcana: 'minor',
    suit: 'wands',
    number: '6',
    keywordsVi: ['chiến thắng hiển hách', 'sự công nhận', 'dẫn đầu xu hướng', 'niềm tin phục hồi'],
    meaningUpright: 'Six of Wands mang tựa đề "Victory" (Chiến Thắng). Sau những nỗ lực đấu tranh không ngừng, bạn đã đạt được thành công xứng đáng. Lá bài báo hiệu sự công nhận từ xã hội, vinh quang gõ cửa và niềm tin bản thân được phục hồi.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự chiến thắng ngắn hạn dễ gây kiêu ngạo nguy hiểm, hoặc sự thất bại do chủ quan khinh địch trước đối thủ.',
    imagePath: '/Thoth_Tarot/thoth-wands-06-victory_6243560100_l.jpg'
  },
  {
    id: 28,
    slug: 'seven-of-wands',
    nameEn: 'Seven of Wands (Valour)',
    nameVi: 'Seven of Wands (Dũng Cảm)',
    arcana: 'minor',
    suit: 'wands',
    number: '7',
    keywordsVi: ['lòng dũng cảm', 'đứng vững bảo vệ', 'đương đầu thử thách', 'ý chí kiên cường'],
    meaningUpright: 'Seven of Wands mang tựa đề "Valour" (Dũng Cảm). Dù phải đối mặt với áp lực số đông hung hãn chống lại mình, bạn vẫn dũng cảm đứng lên bảo vệ quan điểm cá nhân. Sức mạnh tinh thần giúp bạn giữ vững vị thế của mình.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự hoang mang, nhụt chí trước sức ép lớn hoặc việc cố chấp phòng thủ một cách vô vọng thay vì cởi mở đàm phán.',
    imagePath: '/Thoth_Tarot/thoth-wands-07-valour_6243046231_l.jpg'
  },
  {
    id: 29,
    slug: 'eight-of-wands',
    nameEn: 'Eight of Wands (Swiftness)',
    nameVi: 'Eight of Wands (Tốc Độ)',
    arcana: 'minor',
    suit: 'wands',
    number: '8',
    keywordsVi: ['tốc độ nhanh chóng', 'tin tức tức thời', 'sự rõ ràng', 'tiến triển vượt bậc'],
    meaningUpright: 'Eight of Wands mang tựa đề "Swiftness" (Tốc Độ). Năng lượng chuyển dịch cực nhanh mang lại sự tiến triển vượt bậc cho các kế hoạch. Tin tức quan trọng ập đến giúp gỡ bỏ mọi hoài nghi mờ mịt trước đây.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự vội vã, hấp tấp dẫn đến sai sót nghiêm trọng hoặc sự đình trệ, tắc nghẽn thông tin khiến mọi việc bị chậm trễ.',
    imagePath: '/Thoth_Tarot/thoth-wands-08-swiftness_6243049869_l.jpg'
  },
  {
    id: 30,
    slug: 'nine-of-wands',
    nameEn: 'Nine of Wands (Strength)',
    nameVi: 'Nine of Wands (Sức Mạnh)',
    arcana: 'minor',
    suit: 'wands',
    number: '9',
    keywordsVi: ['sức mạnh nội tại', 'sự chuẩn bị phòng thủ', 'khả năng hồi phục', 'sự kiên cường'],
    meaningUpright: 'Nine of Wands mang tựa đề "Strength" (Sức Mạnh). Năng lượng tích lũy đạt đỉnh giúp bạn có sự chuẩn bị vững vàng nhất trước mọi biến cố. Sự kiên cường và sức đề kháng tuyệt vời bảo vệ bạn vượt qua chặng cuối.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự phòng thủ cực đoan thái quá thành đa nghi, hoặc cơ thể bắt đầu kiệt sức do quá căng thẳng kéo dài.',
    imagePath: '/Thoth_Tarot/thoth-wands-09-strength_6243570604_l.jpg'
  },
  {
    id: 31,
    slug: 'ten-of-wands',
    nameEn: 'Ten of Wands (Oppression)',
    nameVi: 'Ten of Wands (Áp Bức)',
    arcana: 'minor',
    suit: 'wands',
    number: '10',
    keywordsVi: ['áp lực đè nặng', 'sự quá tải', 'gánh nặng trách nhiệm', 'ý chí bị đè nén'],
    meaningUpright: 'Ten of Wands mang tựa đề "Oppression" (Áp Bức). Năng lượng lửa bị dồn nén quá mức tạo ra áp lực đè nặng lên vai bạn. Gánh nặng trách nhiệm lớn khiến bạn cảm thấy quá tải và ngột ngạt. Đã đến lúc chia sẻ bớt gánh nặng.',
    meaningReversed: 'Trạng thái ngược phản ánh sự sụp đổ dưới sức ép lớn, hoặc quyết định sáng suốt buông bỏ bớt trách nhiệm không thuộc về mình để tự cứu lấy bản thân.',
    imagePath: '/Thoth_Tarot/thoth-wands-10-oppression_6243056435_l.jpg'
  },
  {
    id: 32,
    slug: 'princess-of-wands',
    nameEn: 'Princess of Wands',
    nameVi: 'Công Chúa Gậy',
    arcana: 'minor',
    suit: 'wands',
    number: '11',
    keywordsVi: ['năng lượng trẻ trung', 'khám phá tự do', 'sự bốc đồng nhiệt huyết', 'kẻ tiên phong'],
    meaningUpright: 'Princess of Wands của Thoth nhảy múa cuồng nhiệt trong vòng lửa thần. Nàng đại diện cho nguồn cảm hứng trẻ trung, sự dũng cảm khám phá thế giới mới mà không e ngại bất cứ điều gì. Đây là sứ giả của những ý tưởng độc bản táo bạo.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự nông nổi, bốc đồng thái quá phá hỏng đại sự, hoặc thói quen cả thèm chóng chán, thiếu kiên nhẫn khi gặp khó khăn ban đầu.',
    imagePath: '/Thoth_Tarot/thoth-wands-11-princess_6243059637_l.jpg'
  },
  {
    id: 33,
    slug: 'prince-of-wands',
    nameEn: 'Prince of Wands',
    nameVi: 'Hoàng Tử Gậy',
    arcana: 'minor',
    suit: 'wands',
    number: '12',
    keywordsVi: ['hành động nhanh chóng', 'lãnh đạo năng nổ', 'sự tự tin', 'lan tỏa năng lượng'],
    meaningUpright: 'Hoàng Tử Gậy điều khiển cỗ xe được kéo bởi con sư tử bờm lửa. Anh là hiện thân của hành động nhanh chóng, tinh thần dám nghĩ dám làm và khả năng lan tỏa năng lượng tích cực lôi kéo đám đông đi theo mình.',
    meaningReversed: 'Trạng thái ngược thể hiện tính khí nóng nảy, độc đoán vô lý hoặc xu hướng lao đầu vào hành động liều lĩnh bất chấp hậu quả gây tổn thương cho người xung quanh.',
    imagePath: '/Thoth_Tarot/thoth-wands-12-prince_6243580006_l.jpg'
  },
  {
    id: 34,
    slug: 'queen-of-wands',
    nameEn: 'Queen of Wands',
    nameVi: 'Nữ Hoàng Gậy',
    arcana: 'minor',
    suit: 'wands',
    number: '13',
    keywordsVi: ['sức hút cá nhân', 'sự ấm áp quý phái', 'khả năng kiến tạo', 'độc lập tự tin'],
    meaningUpright: 'Nữ Hoàng Gậy ngồi kiêu hãnh trên ngai vàng với chú báo đen phủ phục dưới chân. Nàng đại diện cho sức hút cá nhân mãnh liệt, sự ấm áp quý phái, khả năng kiến tạo cuộc sống độc lập và sự tự tin tỏa sáng tuyệt vời.',
    meaningReversed: 'Trạng thái ngược thể hiện sự ghen tị thầm kín, thói thảo mai thâm độc thao túng người khác hoặc xu hướng tự ti, thu mình vào vỏ bọc do sợ thất bại.',
    imagePath: '/Thoth_Tarot/thoth-wands-13-queen_6243065609_l.jpg'
  },
  {
    id: 35,
    slug: 'knight-of-wands',
    nameEn: 'Knight of Wands',
    nameVi: 'Hiệp Sĩ Gậy',
    arcana: 'minor',
    suit: 'wands',
    number: '14',
    keywordsVi: ['tốc độ bão táp', 'chiến đấu kiên cường', 'tính chinh phục', 'tiên phong rực rỡ'],
    meaningUpright: 'Hiệp Sĩ Gậy (tương đương King of Wands ở RWS) phóng ngựa bão táp qua sa mạc. Ông đại diện cho ngọn lửa rực sáng của ý chí chinh phục, tinh thần tiên phong mạnh mẽ đưa mọi ý tưởng hành động đi đến đích cuối cùng.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự kiêu ngạo quá mức, thói quen đốt cháy giai đoạn dẫn đến thất bại thảm hại, hoặc tính khí nóng nảy phá hỏng các mối quan hệ lâu năm.',
    imagePath: '/Thoth_Tarot/thoth-wands-14-knight_6243585618_l.jpg'
  },

  // CUPS (36-49)
  {
    id: 36,
    slug: 'ace-of-cups',
    nameEn: 'Ace of Cups',
    nameVi: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 'ace',
    keywordsVi: ['tình yêu thuần khiết', 'cảm xúc dâng trào', 'mầm sống trực giác', 'sự thức tỉnh tâm hồn'],
    meaningUpright: 'Ace of Cups trong Thoth mô tả chiếc cúp thánh tỏa ra luồng ánh sáng tâm linh thuần khiết chiếu xuống mặt nước. Đây là biểu tượng của tình yêu thương vô điều kiện, sự dâng trào cảm xúc tốt đẹp và trực giác nhạy bén đang trỗi dậy.',
    meaningReversed: 'Trạng thái ngược phản ánh sự cạn kiệt cảm xúc, cảm giác trống rỗng cô đơn bên trong hoặc tình cảm trao đi không được trân trọng đáp lại tương xứng.',
    imagePath: '/Thoth_Tarot/thoth-cups-01-ace_6243176509_l.jpg'
  },
  {
    id: 37,
    slug: 'two-of-cups',
    nameEn: 'Two of Cups (Love)',
    nameVi: 'Two of Cups (Tình Yêu)',
    arcana: 'minor',
    suit: 'cups',
    number: '2',
    keywordsVi: ['tình yêu đôi lứa', 'sự hòa hợp sâu sắc', 'kết nối tâm hồn', 'chia sẻ cảm xúc'],
    meaningUpright: 'Two of Cups mang tựa đề "Love" (Tình Yêu). Dòng chảy cảm xúc tìm thấy sự phản chiếu hoàn hảo ở đối phương. Lá bài đại diện cho sự kết nối tâm hồn sâu sắc, tình yêu đôi lứa hài hòa và sự chia sẻ thấu hiểu lẫn nhau.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự rạn nứt tình cảm, bất đồng quan điểm sâu sắc trong mối quan hệ hoặc sự ích kỷ từ một phía phá vỡ thế cân bằng cảm xúc.',
    imagePath: '/Thoth_Tarot/thoth-cups-02-love_6243699186_l.jpg'
  },
  {
    id: 38,
    slug: 'three-of-cups',
    nameEn: 'Three of Cups (Abundance)',
    nameVi: 'Three of Cups (Trù Phú)',
    arcana: 'minor',
    suit: 'cups',
    number: '3',
    keywordsVi: ['sự trù phú cảm xúc', 'ăn mừng chia sẻ', 'tình bạn gắn kết', 'sự sinh trưởng ngọt ngào'],
    meaningUpright: 'Three of Cups mang tựa đề "Abundance" (Trù Phú). Ba chiếc chén vàng tràn đầy sữa ngọt ngào ngụ ý sự viên mãn về mặt tình cảm. Đây là lúc chia sẻ niềm vui với bạn bè, ăn mừng những cột mốc ý nghĩa cùng nhau.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự hoang phí tình cảm vào những cuộc vui vô bổ, cảm giác cô đơn lạc lõng ngay trong đám đông bạn bè, hoặc sự đố kỵ ngầm.',
    imagePath: '/Thoth_Tarot/thoth-cups-03-abundance_6243703544_l.jpg'
  },
  {
    id: 39,
    slug: 'four-of-cups',
    nameEn: 'Four of Cups (Luxury)',
    nameVi: 'Four of Cups (Xa Hoa)',
    arcana: 'minor',
    suit: 'cups',
    number: '4',
    keywordsVi: ['xa hoa dư thừa', 'sự chán chường', 'thiếu trân trọng', 'đóng cửa lòng'],
    meaningUpright: 'Four of Cups mang tựa đề "Luxury" (Xa Hoa). Sự dư dật về vật chất lẫn tình cảm không đem lại hạnh phúc mà trái lại tạo ra cảm giác ngấy chán, mệt mỏi. Bạn đang đóng cửa lòng trước những cơ hội cảm xúc mới bên ngoài.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự thức tỉnh từ trạng thái u uất chán nản, cởi mở đón nhận nguồn năng lượng tươi mới và quyết tâm thay đổi góc nhìn cuộc sống.',
    imagePath: '/Thoth_Tarot/thoth-cups-04-luxury_6243190683_l.jpg'
  },
  {
    id: 40,
    slug: 'five-of-cups',
    nameEn: 'Five of Cups (Disappointment)',
    nameVi: 'Five of Cups (Thất Vọng)',
    arcana: 'minor',
    suit: 'cups',
    number: '5',
    keywordsVi: ['thất vọng đau đớn', 'nuối tiếc mất mát', 'sự cô độc', 'kỳ vọng đổ vỡ'],
    meaningUpright: 'Five of Cups mang tựa đề "Disappointment" (Thất Vọng). Kỳ vọng lớn đổ vỡ đem lại nỗi đau đớn và nuối tiếc khôn nguôi. Hãy nhìn nhận thực tế một cách trung thực nhất thay vì tự dằn vặt bản thân trong thất bại.',
    meaningReversed: 'Trạng thái ngược cho thấy sự chấp nhận nỗi đau quá khứ để bước qua, hàn gắn vết thương lòng và bắt đầu nhận ra những điều tốt đẹp vẫn còn sót lại.',
    imagePath: '/Thoth_Tarot/thoth-cups-05-disappointment_6243712810_l.jpg'
  },
  {
    id: 41,
    slug: 'six-of-cups',
    nameEn: 'Six of Cups (Pleasure)',
    nameVi: 'Six of Cups (Niềm Vui)',
    arcana: 'minor',
    suit: 'cups',
    number: '6',
    keywordsVi: ['niềm vui thơ ấu', 'sự hoài niệm', 'hàn gắn tâm hồn', 'trao đổi tự nhiên'],
    meaningUpright: 'Six of Cups mang tựa đề "Pleasure" (Niềm Vui). Lá bài đưa ta về trạng thái trong trẻo ngọt ngào của những ký ức xưa cũ lành mạnh. Nguồn dinh dưỡng cảm xúc từ quá khứ giúp hàn gắn những tổn thương hiện tại.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói quen sống bám víu vào hào quang quá khứ, không dám đối diện với trách nhiệm trưởng thành của thực tại cuộc sống.',
    imagePath: '/Thoth_Tarot/thoth-cups-06-pleasure_6243717776_l.jpg'
  },
  {
    id: 42,
    slug: 'seven-of-cups',
    nameEn: 'Seven of Cups (Debauch)',
    nameVi: 'Seven of Cups (Trụy Lạc)',
    arcana: 'minor',
    suit: 'cups',
    number: '7',
    keywordsVi: ['ảo vọng độc hại', 'sự mê muội', 'lựa chọn lừa dối', 'thiếu kỷ luật cảm xúc'],
    meaningUpright: 'Seven of Cups mang tựa đề "Debauch" (Trụy Lạc). Bạn đang bị vây hãm bởi quá nhiều ảo vọng mê muội, những thói quen nuông chiều bản thân thái quá có hại. Cần tỉnh táo thanh lọc tâm trí trước khi đưa ra quyết định.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự thức tỉnh kịp thời thoát khỏi những ảo tưởng sai lệch, xác lập mục tiêu thực tế và lấy lại kỷ luật cảm xúc bản thân.',
    imagePath: '/Thoth_Tarot/thoth-cups-07-debauch_6243205467_l.jpg'
  },
  {
    id: 43,
    slug: 'eight-of-cups',
    nameEn: 'Eight of Cups (Indolence)',
    nameVi: 'Eight of Cups (Trì Trệ)',
    arcana: 'minor',
    suit: 'cups',
    number: '8',
    keywordsVi: ['sự uể oải', 'bỏ cuộc ra đi', 'mất động lực', 'tìm kiếm giá trị mới'],
    meaningUpright: 'Eight of Cups mang tựa đề "Indolence" (Trì Trệ). Cảm xúc bị khô cạn hoàn toàn tạo ra trạng thái uể oải, mất hết động lực. Bạn nhận ra cấu trúc hiện tại không còn đem lại giá trị tinh thần nào và quyết định lặng lẽ ra đi.',
    meaningReversed: 'Trạng thái ngược thể hiện sự do dự, e sợ thay đổi khiến bạn cố bám víu lấy một hoàn cảnh tẻ nhạt đã chết mòn năng lượng cảm xúc.',
    imagePath: '/Thoth_Tarot/thoth-cups-08-indolence_6243726692_l.jpg'
  },
  {
    id: 44,
    slug: 'nine-of-cups',
    nameEn: 'Nine of Cups (Happiness)',
    nameVi: 'Nine of Cups (Hạnh Phúc)',
    arcana: 'minor',
    suit: 'cups',
    number: '9',
    keywordsVi: ['hài lòng tự tại', 'ước nguyện thành sự thật', 'sự viên mãn nội tâm', 'hòa hợp'],
    meaningUpright: 'Nine of Cups mang tựa đề "Happiness" (Hạnh Phúc). Sự hòa hợp sâu sắc giữa ý chí và cảm xúc mang lại cảm giác viên mãn tự tại nhất. Mọi ước nguyện chân chính của bạn đều có cơ hội hiển lộ thành sự thật.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự tự mãn ích kỷ, nuông chiều thói ham muốn vật chất quá mức dẫn đến mất đi ý nghĩa hạnh phúc thực sự sâu sắc.',
    imagePath: '/Thoth_Tarot/thoth-cups-09-happiness_6243731676_l.jpg'
  },
  {
    id: 45,
    slug: 'ten-of-cups',
    nameEn: 'Ten of Cups (Satiety)',
    nameVi: 'Ten of Cups (Bão Hòa)',
    arcana: 'minor',
    suit: 'cups',
    number: '10',
    keywordsVi: ['bão hòa cảm xúc', 'sự hoàn thành mỹ mãn', 'hòa hợp gia đình', 'kết thúc chu kỳ'],
    meaningUpright: 'Ten of Cups mang tựa đề "Satiety" (Bão Hòa). Dòng chảy cảm xúc đã lấp đầy hoàn toàn vương quốc nội tâm. Sự hoàn thành mỹ mãn mang lại bình yên sâu sắc cho gia đình và các mối quan hệ thân thiết nhất.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự bão hòa biến thành ngấy chán, những mâu thuẫn ngầm trong gia đình che đậy dưới vỏ bọc bình yên giả tạo bên ngoài.',
    imagePath: '/Thoth_Tarot/thoth-cups-10-satiety_6243219077_l.jpg'
  },
  {
    id: 46,
    slug: 'princess-of-cups',
    nameEn: 'Princess of Cups',
    nameVi: 'Công Chúa Chén',
    arcana: 'minor',
    suit: 'cups',
    number: '11',
    keywordsVi: ['nhạy cảm tinh tế', 'trực giác thơ mộng', 'tình yêu lãng mạn', 'khởi đầu cảm xúc'],
    meaningUpright: 'Công Chúa Chén nhảy múa dịu dàng với chú rùa và hoa sen nhô lên từ chén nước. Nàng đại diện cho tâm hồn nhạy cảm tinh tế, trí tưởng tượng thơ mộng và những rung động lãng mạn đầu tiên của trái tim.',
    meaningReversed: 'Trạng thái ngược thể hiện sự ủy mị ướt át thái quá, tính khí thất thường dễ tự ái vặt hoặc sự trốn tránh thực tế cuộc sống vào thế giới mộng mơ phi lý.',
    imagePath: '/Thoth_Tarot/thoth-cups-11-princess_6243223747_l.jpg'
  },
  {
    id: 47,
    slug: 'prince-of-cups',
    nameEn: 'Prince of Cups',
    nameVi: 'Hoàng Tử Chén',
    arcana: 'minor',
    suit: 'cups',
    number: '12',
    keywordsVi: ['sức hấp dẫn thầm lặng', 'sự tinh tế trí tuệ', 'nghệ sĩ chiều sâu', 'thao túng cảm xúc'],
    meaningUpright: 'Hoàng Tử Chén ngồi trên xe kéo bởi chú đại bàng uy nghiêm. Anh sở hữu sức hấp dẫn thầm lặng, thế giới nội tâm sâu sắc của một nghệ sĩ đích thực và trí tuệ thấu suốt tâm lý người khác một cách tinh tế.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự lạnh lùng tàn nhẫn giấu sau vỏ bọc dịu dàng, thói thao túng cảm xúc tinh vi hoặc sự lừa dối trong chuyện tình cảm tình yêu.',
    imagePath: '/Thoth_Tarot/thoth-cups-12-prince_6243745720_l.jpg'
  },
  {
    id: 48,
    slug: 'queen-of-cups',
    nameEn: 'Queen of Cups',
    nameVi: 'Nữ Hoàng Chén',
    arcana: 'minor',
    suit: 'cups',
    number: '13',
    keywordsVi: ['thấu cảm tuyệt đối', 'người mẹ tinh thần', 'trực giác thấu suốt', 'sự tĩnh lặng'],
    meaningUpright: 'Nữ Hoàng Chén ngồi giữa làn nước huyền sương với chiếc cúp hình vỏ sò kỳ bí. Nàng là hiện thân của lòng thấu cảm tuyệt đối, khả năng lắng nghe và nuôi dưỡng tinh thần ấm áp cho những ai đang chịu tổn thương sâu sắc.',
    meaningReversed: 'Trạng thái ngược chỉ ra xu hướng phụ thuộc cảm xúc nặng nề, thói ghen tuông cuồng loạn hoặc sự tự cô lập bản thân do quá nhạy cảm trước môi trường ngoài.',
    imagePath: '/Thoth_Tarot/thoth-cups-13-queen_6243750344_l.jpg'
  },
  {
    id: 49,
    slug: 'knight-of-cups',
    nameEn: 'Knight of Cups',
    nameVi: 'Hiệp Sĩ Chén',
    arcana: 'minor',
    suit: 'cups',
    number: '14',
    keywordsVi: ['sứ giả tình yêu', 'nhiệt huyết cảm xúc', 'lòng trắc ẩn', 'hành trình tâm linh'],
    meaningUpright: 'Hiệp Sĩ Chén (tương đương King of Cups ở RWS) cưỡi con ngựa trắng thong thả mang chiếc chén phát sáng. Ông đại diện cho tình yêu thương rộng lớn, lòng trắc ẩn bao dung và sự cống hiến hết mình cho các giá trị nhân văn cao đẹp.',
    meaningReversed: 'Trạng thái ngược thể hiện sự yếu đuối nhu nhược trong hành động, thói đạo đức giả lợi dụng lòng tốt của người khác, hoặc sự cạn kiệt tình thương.',
    imagePath: '/Thoth_Tarot/thoth-cups-14-knight_6243238063_l.jpg'
  },

  // SWORDS (50-63)
  {
    id: 50,
    slug: 'ace-of-swords',
    nameEn: 'Ace of Swords',
    nameVi: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 'ace',
    keywordsVi: ['trí tuệ sắc bén', 'sự sáng suốt', 'phán quyết công bằng', 'ý tưởng đột phá'],
    meaningUpright: 'Ace of Swords trong Thoth mô tả thanh gươm thần xuyên qua vương miện ánh sáng. Đây là biểu tượng của tư duy logic sắc bén, sự sáng tỏ tuyệt đối của trí tuệ đập tan mọi ảo ảnh lừa mị để tìm ra chân lý tối thượng.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự lạm dụng trí tuệ để phá hủy, những suy nghĩ độc hại gây tổn thương sâu sắc, hoặc sự nhầm lẫn nghiêm trọng trong phán đoán.',
    imagePath: '/Thoth_Tarot/thoth-swords-01-ace_6243119861_l.jpg'
  },
  {
    id: 51,
    slug: 'two-of-swords',
    nameEn: 'Two of Swords (Peace)',
    nameVi: 'Two of Swords (Hòa Bình)',
    arcana: 'minor',
    suit: 'swords',
    number: '2',
    keywordsVi: ['hòa bình cân bằng', 'tĩnh lặng tư duy', 'sự thỏa hiệp tạm thời', 'quyết định lý trí'],
    meaningUpright: 'Two of Swords mang tựa đề "Peace" (Hòa Bình). Hai thanh kiếm bắt chéo nâng đỡ đóa hồng xanh ngụ ý tư duy đạt đến trạng thái cân bằng tĩnh lặng. Đây là lúc giải quyết mâu thuẫn bằng lý trí khách quan hòa nhã.',
    meaningReversed: 'Trạng thái ngược phản ánh sự thỏa hiệp giả tạo, sự căng thẳng ngầm âm ỉ bên trong hoặc việc không dám đưa ra lựa chọn rõ ràng vì sợ mất lòng.',
    imagePath: '/Thoth_Tarot/thoth-swords-02-peace_6243640604_l.jpg'
  },
  {
    id: 52,
    slug: 'three-of-swords',
    nameEn: 'Three of Swords (Sorrow)',
    nameVi: 'Three of Swords (U Sầu)',
    arcana: 'minor',
    suit: 'swords',
    number: '3',
    keywordsVi: ['u sầu sâu sắc', 'rạn nứt tư duy', 'nỗi đau chia ly', 'sự thanh lọc trí tuệ'],
    meaningUpright: 'Three of Swords mang tựa đề "Sorrow" (U Sầu). Ba thanh kiếm đâm nát đóa hồng đại diện cho sự tan vỡ đau đớn của các ảo tưởng cảm xúc dưới nhát chém tàn nhẫn của sự thật trí tuệ. Cần chấp nhận để thanh lọc.',
    meaningReversed: 'Trạng thái ngược cho thấy sự níu kéo nỗi đau khổ dai dẳng, thói dằn vặt bản thân u uất không chịu buông xả để tự cứu lấy tâm hồn mình.',
    imagePath: '/Thoth_Tarot/thoth-swords-03-sorrow_6243127065_l.jpg'
  },
  {
    id: 53,
    slug: 'four-of-swords',
    nameEn: 'Four of Swords (Truce)',
    nameVi: 'Four of Swords (Đình Chiến)',
    arcana: 'minor',
    suit: 'swords',
    number: '4',
    keywordsVi: ['đình chiến hồi sức', 'tĩnh dưỡng phục hồi', 'rút lui thông minh', 'chuẩn bị năng lượng'],
    meaningUpright: 'Four of Swords mang tựa đề "Truce" (Đình Chiến). Bốn thanh kiếm hội tụ về tâm đóa hồng chỉ ra giai đoạn nghỉ ngơi tĩnh dưỡng cần thiết sau tranh đấu. Hãy rút lui thông minh để hồi phục năng lượng trí tuệ.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự bắt đầu lại quá sớm khi chưa hồi phục hoàn toàn, hoặc sự trì trệ lười biếng kéo dài không muốn quay lại hành động.',
    imagePath: '/Thoth_Tarot/thoth-swords-04-truce_6243648646_l.jpg'
  },
  {
    id: 54,
    slug: 'five-of-swords',
    nameEn: 'Five of Swords (Defeat)',
    nameVi: 'Five of Swords (Thất Bại)',
    arcana: 'minor',
    suit: 'swords',
    number: '5',
    keywordsVi: ['thất bại thảm hại', 'sự phản bội', 'nỗi sợ hãi thất thoát', 'giới hạn trí tuệ'],
    meaningUpright: 'Five of Swords mang tựa đề "Defeat" (Thất Bại). Ý chí kiêu ngạo gặp phải rào cản quá lớn dẫn đến thất bại đắng cay. Lá bài chỉ ra những giới hạn của trí tuệ phàm trần và cảnh báo nguy cơ phản bội xung quanh.',
    meaningReversed: 'Trạng thái ngược phản ánh nỗi sợ thất bại ám ảnh ngăn cản bạn hành động, hoặc sự trả đũa hằn học tiêu cực làm tổn thương cả hai phía.',
    imagePath: '/Thoth_Tarot/thoth-swords-05-defeat_6243653174_l.jpg'
  },
  {
    id: 55,
    slug: 'six-of-swords',
    nameEn: 'Six of Swords (Science)',
    nameVi: 'Six of Swords (Khoa Học)',
    arcana: 'minor',
    suit: 'swords',
    number: '6',
    keywordsVi: ['tư duy khoa học', 'sự sáng suốt khách quan', 'giải pháp thực tế', 'chuyển biến tích cực'],
    meaningUpright: 'Six of Swords mang tựa đề "Science" (Khoa Học). Trí tuệ đạt đến sự sáng suốt khách quan cao nhất, tìm ra giải pháp thực tế tối ưu nhất cho vấn đề phức tạp. Con thuyền tư duy bắt đầu chuyển sang bến đỗ bình yên.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự bế tắc tư duy do thiếu khách quan, hoặc việc từ chối nhìn nhận sự thật logic khiến bạn luẩn quẩn trong khó khăn.',
    imagePath: '/Thoth_Tarot/thoth-swords-06-science_6243140105_l.jpg'
  },
  {
    id: 56,
    slug: 'seven-of-swords',
    nameEn: 'Seven of Swords (Futility)',
    nameVi: 'Seven of Swords (Vô Ích)',
    arcana: 'minor',
    suit: 'swords',
    number: '7',
    keywordsVi: ['vô ích vô vọng', 'sự lừa dối âm thầm', 'kế hoạch thất bại', 'thiếu trung thực'],
    meaningUpright: 'Seven of Swords mang tựa đề "Futility" (Vô Ích). Mọi mưu tính lách luật, thiếu trung thực hoặc trốn tránh trách nhiệm đều sẽ dẫn đến kết quả vô vọng. Hãy đối diện thẳng thắn thay vì đi đường tắt mạo hiểm.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự phanh phui những âm mưu gian dối, hoặc sự thức tỉnh nhận ra kế hoạch hiện tại hoàn toàn bất khả thi để kịp thời dừng lại.',
    imagePath: '/Thoth_Tarot/thoth-swords-07-futility_6243661116_l.jpg'
  },
  {
    id: 57,
    slug: 'eight-of-swords',
    nameEn: 'Eight of Swords (Interference)',
    nameVi: 'Eight of Swords (Can Thiệp)',
    arcana: 'minor',
    suit: 'swords',
    number: '8',
    keywordsVi: ['sự can thiệp cản trở', 'suy nghĩ hạn hẹp', 'sự do dự phân tâm', 'tự trói buộc'],
    meaningUpright: 'Eight of Swords mang tựa đề "Interference" (Can Thiệp). Quá nhiều suy nghĩ vụn vặt và sự can thiệp từ ý kiến bên ngoài khiến bạn bị phân tâm, do dự không thể đưa ra hành động quyết đoán. Bạn đang tự trói buộc mình.',
    meaningReversed: 'Trạng thái ngược thể hiện việc gạt bỏ được những nhiễu loạn xung quanh, lấy lại sự tập trung tư duy để tự giải thoát khỏi vỏ bọc sợ hãi.',
    imagePath: '/Thoth_Tarot/thoth-swords-08-interference_6243147975_l.jpg'
  },
  {
    id: 58,
    slug: 'nine-of-swords',
    nameEn: 'Nine of Swords (Cruelty)',
    nameVi: 'Nine of Swords (Tàn Nhẫn)',
    arcana: 'minor',
    suit: 'swords',
    number: '9',
    keywordsVi: ['tự hoại tàn nhẫn', 'ác mộng ám ảnh', 'nỗi dằn vặt tội lỗi', 'sự đau khổ tinh thần'],
    meaningUpright: 'Nine of Swords mang tựa đề "Cruelty" (Tàn Nhẫn). Lá bài chỉ ra trạng thái tự hoại tàn nhẫn nhất của tâm trí thông qua nỗi dằn vặt tội lỗi, ác mộng ám ảnh và sự lo âu tột độ. Hãy ngừng tự hành hạ bản thân.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự chấm dứt của cơn khủng hoảng tinh thần, ánh sáng ý thức xua tan bóng tối sợ hãi mơ hồ và bắt đầu quá trình phục hồi.',
    imagePath: '/Thoth_Tarot/thoth-swords-09-cruelty_6243152607_l.jpg'
  },
  {
    id: 59,
    slug: 'ten-of-swords',
    nameEn: 'Ten of Swords (Ruin)',
    nameVi: 'Ten of Swords (Hủy Diệt)',
    arcana: 'minor',
    suit: 'swords',
    number: '10',
    keywordsVi: ['sụp đổ hoàn toàn', 'hủy diệt cấu trúc', 'chạm đáy nỗi đau', 'sự kết thúc triệt để'],
    meaningUpright: 'Ten of Swords mang tựa đề "Ruin" (Hủy Diệt). Mười thanh kiếm đâm nát đóa hồng đại diện cho sự sụp đổ hoàn toàn của cấu trúc tư duy cũ. Mọi thứ đã chạm đáy nỗi đau, không thể tồi tệ hơn được nữa. Chỉ còn đường đi lên.',
    meaningReversed: 'Trạng thái ngược báo hiệu sự tái sinh kỳ diệu từ đống tro tàn đổ nát, bắt đầu xây dựng lại cuộc sống trên nền tảng nhận thức mới vững chãi hơn.',
    imagePath: '/Thoth_Tarot/thoth-swords-10-ruin_6243673476_l.jpg'
  },
  {
    id: 60,
    slug: 'princess-of-swords',
    nameEn: 'Princess of Swords',
    nameVi: 'Công Chúa Kiếm',
    arcana: 'minor',
    suit: 'swords',
    number: '11',
    keywordsVi: ['trí tuệ sắc sảo', 'sự truy xét chân lý', 'chiến binh phản biện', 'năng lượng nổi loạn'],
    meaningUpright: 'Công Chúa Kiếm đứng vững trên bệ đá thiêng, giương cao thanh gươm sẵn sàng chiến đấu bảo vệ công lý. Nàng đại diện cho trí tuệ sắc sảo, tinh thần phản biện mạnh mẽ và sự dũng cảm truy xét chân lý đến cùng.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói xoi mói, khẩu chiến độc hại làm tổn thương người khác, hoặc sự phản kháng nổi loạn thiếu suy nghĩ chín chắn.',
    imagePath: '/Thoth_Tarot/thoth-swords-11-princess_6243677676_l.jpg'
  },
  {
    id: 61,
    slug: 'prince-of-swords',
    nameEn: 'Prince of Swords',
    nameVi: 'Hoàng Tử Kiếm',
    arcana: 'minor',
    suit: 'swords',
    number: '12',
    keywordsVi: ['tư duy logic vượt bậc', 'kế hoạch sắc bén', 'sự khách quan tàn nhẫn', 'thiếu kiên nhẫn'],
    meaningUpright: 'Hoàng Tử Kiếm bay trên cỗ xe mây lướt gió tốc độ cao. Anh sở hữu tư duy logic vượt bậc, khả năng lập kế hoạch sắc bén và sự khách quan thực tế cao độ để giải quyết mọi rắc rối phức tạp.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự lạnh lùng tàn nhẫn trong giao tiếp, thói phán xét phiến diện hoặc sự thiếu kiên nhẫn, cả thèm chóng chán khi thực thi kế hoạch.',
    imagePath: '/Thoth_Tarot/thoth-swords-12-prince_6243164463_l.jpg'
  },
  {
    id: 62,
    slug: 'queen-of-swords',
    nameEn: 'Queen of Swords',
    nameVi: 'Nữ Hoàng Kiếm',
    arcana: 'minor',
    suit: 'swords',
    number: '13',
    keywordsVi: ['trí tuệ độc lập', 'sự sáng tỏ đau đớn', 'ranh giới vững chắc', 'sự công minh'],
    meaningUpright: 'Nữ Hoàng Kiếm ngồi trên ngai mây cao ngất, cầm thanh gươm chém đứt tấm màng ảo ảnh che mắt. Nàng là biểu tượng của trí tuệ độc lập tự chủ, khả năng thiết lập ranh giới bảo vệ bản thân và sự công minh tuyệt đối.',
    meaningReversed: 'Trạng thái ngược chỉ ra thói cay nghiệt, định kiến sâu sắc hoặc sự cô độc lạnh lẽo tự tạo do dựng rào cản quá lớn chống lại thế giới bên ngoài.',
    imagePath: '/Thoth_Tarot/thoth-swords-13-queen_6243168663_l.jpg'
  },
  {
    id: 63,
    slug: 'knight-of-swords',
    nameEn: 'Knight of Swords',
    nameVi: 'Hiệp Sĩ Kiếm',
    arcana: 'minor',
    suit: 'swords',
    number: '14',
    keywordsVi: ['tấn công trí tuệ', 'sự phán quyết quyết đoán', 'lãnh đạo tư duy', 'chiến binh công lý'],
    meaningUpright: 'Hiệp Sĩ Kiếm (tương đương King of Swords ở RWS) lao vút đi giữa giông bão với đôi cánh chim ưng. Ông đại diện cho sự phán quyết quyết đoán, năng lực lãnh đạo tư duy xuất sắc đưa mọi ý tưởng đi đến hành động triệt để.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói bạo chúa độc tài tư tưởng, sự tàn nhẫn trong các quyết định sa thải hoặc thói ba hoa tự phụ thiếu thực tế.',
    imagePath: '/Thoth_Tarot/thoth-swords-14-knight_6243172617_l.jpg'
  },

  // PENTACLES / DISKS (64-77)
  {
    id: 64,
    slug: 'ace-of-pentacles',
    nameEn: 'Ace of Disks',
    nameVi: 'Ace of Disks',
    arcana: 'minor',
    suit: 'pentacles',
    number: 'ace',
    keywordsVi: ['vật chất sơ khởi', 'sự trù phú trần gian', 'hạt giống tài chính', 'sức khỏe vững chắc'],
    meaningUpright: 'Ace of Disks trong Thoth thể hiện chiếc Đĩa tròn mang ấn ký thái cực và triết lý thiên địa nhân hòa hợp. Đây là hạt giống trù phú sơ khởi của vật chất, tài chính và sức khỏe thể chất vững chắc đang chờ bạn gieo trồng.',
    meaningReversed: 'Trạng thái ngược phản ánh sự bỏ lỡ cơ hội kinh doanh thực tế, sự tổn hao tài chính ban đầu hoặc tình trạng sức khỏe suy giảm do thiếu chăm sóc bản thân.',
    imagePath: '/Thoth_Tarot/thoth-disks-01-ace_6243588832_l.jpg'
  },
  {
    id: 65,
    slug: 'two-of-pentacles',
    nameEn: 'Two of Disks (Change)',
    nameVi: 'Two of Disks (Thay Đổi)',
    arcana: 'minor',
    suit: 'pentacles',
    number: '2',
    keywordsVi: ['sự thay đổi linh hoạt', 'chu chuyển năng lượng', 'cân bằng tài chính', 'thích ứng cao'],
    meaningUpright: 'Two of Disks mang tựa đề "Change" (Thay Đổi). Hai chiếc đĩa được kết nối bởi con rắn Ouroboros ngụ ý sự xoay vòng và chu chuyển liên tục của năng lượng vật chất. Bạn cần linh hoạt thích ứng để giữ cân bằng.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự mất thăng bằng do quá nhiều việc dồn dập, hoặc sự bất ổn tài chính do chi tiêu thiếu tính toán dài hạn.',
    imagePath: '/Thoth_Tarot/thoth-disks-02-change_6243591978_l.jpg'
  },
  {
    id: 66,
    slug: 'three-of-pentacles',
    nameEn: 'Three of Disks (Works)',
    nameVi: 'Three of Disks (Kiến Thiết)',
    arcana: 'minor',
    suit: 'pentacles',
    number: '3',
    keywordsVi: ['kiến thiết cấu trúc', 'tay nghề điêu luyện', 'hợp tác chuyên môn', 'sự thực thi vững vàng'],
    meaningUpright: 'Three of Disks mang tựa đề "Works" (Kiến Thiết). Ba bánh xe bánh răng khớp vào nhau hoàn hảo thể hiện sự thực thi vững vàng của kế hoạch. Sự hợp tác chuyên môn chặt chẽ mang lại cấu trúc vật chất tốt đẹp.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự thiếu tập trung chuyên môn, làm việc cẩu thả vô kỷ luật hoặc sự bất hòa bất hợp tác phá hỏng tiến độ chung của công trình.',
    imagePath: '/Thoth_Tarot/thoth-disks-03-works_6243595360_l.jpg'
  },
  {
    id: 67,
    slug: 'four-of-pentacles',
    nameEn: 'Four of Disks (Power)',
    nameVi: 'Four of Disks (Bảo Thủ)',
    arcana: 'minor',
    suit: 'pentacles',
    number: '4',
    keywordsVi: ['ổn định vững chắc', 'sự bảo thủ', 'tích lũy an toàn', 'đề phòng rủi ro'],
    meaningUpright: 'Four of Disks mang tựa đề "Power" (Sức Mạnh/Bảo Thủ). Bốn chiếc đĩa tạo thành một pháo đài phòng thủ kiên cố bảo vệ tài sản tích lũy. Bạn đề cao sự an toàn tuyệt đối và từ chối mọi rủi ro đầu tư.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự keo kiệt bủn xỉn thái quá gây cản trở dòng chảy tài chính, hoặc sự sụp đổ bất ngờ của pháo đài do quá cứng nhắc.',
    imagePath: '/Thoth_Tarot/thoth-disks-04-power_6243598712_l.jpg'
  },
  {
    id: 68,
    slug: 'five-of-pentacles',
    nameEn: 'Five of Disks (Worry)',
    nameVi: 'Five of Disks (Lo Âu)',
    arcana: 'minor',
    suit: 'pentacles',
    number: '5',
    keywordsVi: ['lo âu tài chính', 'suy nhược tinh thần', 'cảm giác thiếu thốn', 'khủng hoảng vật chất'],
    meaningUpright: 'Five of Disks mang tựa đề "Worry" (Lo Âu). Sự mất cân đối nghiêm trọng về năng lượng vật chất tạo ra nỗi lo sợ thiếu thốn tiền bạc và suy nhược sức khỏe tinh thần. Cần bình tĩnh tái thiết lập trật tự.',
    meaningReversed: 'Trạng thái ngược thể hiện sự vượt qua được giai đoạn khủng hoảng khó khăn nhất, tìm thấy sự giúp đỡ tài chính hoặc hồi phục thể chất kỳ diệu.',
    imagePath: '/Thoth_Tarot/thoth-disks-05-worry_6243602064_l.jpg'
  },
  {
    id: 69,
    slug: 'six-of-pentacles',
    nameEn: 'Six of Disks (Success)',
    nameVi: 'Six of Disks (Thành Công)',
    arcana: 'minor',
    suit: 'pentacles',
    number: '6',
    keywordsVi: ['thành công hài hòa', 'sự hào phóng', 'sự công bằng tài chính', 'nhận quả ngọt'],
    meaningUpright: 'Six of Disks mang tựa đề "Success" (Thành Công). Sáu chiếc đĩa sắp xếp thành hình lục giác cân đối hoàn hảo. Lá bài mang thông điệp của sự thành công hài hòa, dòng chảy tài chính lành mạnh và lòng hào phóng chia sẻ đúng chỗ.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự hào phóng sai chỗ tạo sự ỷ lại, thói phân chia lợi ích bất công hoặc nợ nần tài chính phát sinh ngoài tầm kiểm soát.',
    imagePath: '/Thoth_Tarot/thoth-disks-06-success_6243088205_l.jpg'
  },
  {
    id: 70,
    slug: 'seven-of-pentacles',
    nameEn: 'Seven of Disks (Failure)',
    nameVi: 'Seven of Disks (Thất Bại)',
    arcana: 'minor',
    suit: 'pentacles',
    number: '7',
    keywordsVi: ['thất vọng thu hoạch', 'sự đình trệ', 'suy giảm năng suất', 'kiên nhẫn xem xét'],
    meaningUpright: 'Seven of Disks mang tựa đề "Failure" (Thất Bại). Đất đai khô cằn khiến sản lượng thu hoạch suy giảm nghiêm trọng. Kế hoạch bị đình trệ khiến bạn thất vọng. Hãy kiên nhẫn xem xét lại phương pháp thay vì bỏ cuộc.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự lãng phí công sức nghiêm trọng do đầu tư sai chỗ, hoặc quyết định sáng suốt dừng dự án không hiệu quả để cắt lỗ.',
    imagePath: '/Thoth_Tarot/thoth-disks-07-failure_6243091133_l.jpg'
  },
  {
    id: 71,
    slug: 'eight-of-pentacles',
    nameEn: 'Eight of Disks (Prudence)',
    nameVi: 'Eight of Disks (Thận Trọng)',
    arcana: 'minor',
    suit: 'pentacles',
    number: '8',
    keywordsVi: ['thận trọng tỉ mỉ', 'sự rèn luyện kỹ năng', 'tích lũy từng bước', 'chăm chỉ'],
    meaningUpright: 'Eight of Disks mang tựa đề "Prudence" (Thận Trọng). Tám chiếc đĩa được chăm chút tỉ mỉ thể hiện tinh thần rèn luyện tay nghề nghiêm túc. Thành quả lớn đến từ việc tích lũy bền bỉ và cẩn trọng từng bước nhỏ.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói hấp tấp đốt cháy giai đoạn gây hư hỏng sản phẩm, hoặc thói lười biếng bỏ bê rèn luyện kỹ năng cá nhân.',
    imagePath: '/Thoth_Tarot/thoth-disks-08-prudence_6243611828_l.jpg'
  },
  {
    id: 72,
    slug: 'nine-of-pentacles',
    nameEn: 'Nine of Disks (Gain)',
    nameVi: 'Nine of Disks (Thành Quả)',
    arcana: 'minor',
    suit: 'pentacles',
    number: '9',
    keywordsVi: ['thu hoạch lớn', 'sự tự do tài chính', 'hưởng thụ thành quả', 'thịnh vượng'],
    meaningUpright: 'Nine of Disks mang tựa đề "Gain" (Thành Quả). Sự kết hợp hoàn hảo giữa cơ hội và nỗ lực bền bỉ đem lại thu hoạch tài chính cực lớn. Bạn được tận hưởng sự tự do vật chất và sự thịnh vượng xứng đáng.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự hoang phí tài sản vào những thứ xa xỉ vô bổ, hoặc sự mất mát của cải do quản lý lỏng lẻo thiếu an toàn.',
    imagePath: '/Thoth_Tarot/thoth-disks-09-gain_6243098627_l.jpg'
  },
  {
    id: 73,
    slug: 'ten-of-pentacles',
    nameEn: 'Ten of Disks (Wealth)',
    nameVi: 'Ten of Disks (Thịnh Vượng)',
    arcana: 'minor',
    suit: 'pentacles',
    number: '10',
    keywordsVi: ['sự giàu có vững bền', 'di sản gia đình', 'an toàn vật chất', 'viên mãn thịnh vượng'],
    meaningUpright: 'Ten of Disks mang tựa đề "Wealth" (Thịnh Vượng). Mười chiếc đĩa xếp thành mô hình Cây Sự Sống vững chãi nhất. Lá bài đại diện cho sự giàu có vững bền lâu đời, di sản gia tộc tốt đẹp và sự an toàn vật chất tuyệt đối.',
    meaningReversed: 'Trạng thái ngược cảnh báo những tranh chấp tài sản gia đình gay gắt, sự suy thoái tài chính do đầu tư mạo hiểm ngu ngốc hoặc rủi ro pháp lý.',
    imagePath: '/Thoth_Tarot/thoth-disks-10-wealth_6243102541_l.jpg'
  },
  {
    id: 74,
    slug: 'princess-of-pentacles',
    nameEn: 'Princess of Disks',
    nameVi: 'Công Chúa Đĩa',
    arcana: 'minor',
    suit: 'pentacles',
    number: '11',
    keywordsVi: ['thai nghén ý tưởng', 'kết nối thiên nhiên', 'sự kiên nhẫn', 'tiềm năng vật chất'],
    meaningUpright: 'Công Chúa Đĩa mang thai nghén hạt giống sự sống mới bên trong chiếc đĩa thiêng. Nàng đại diện cho sự kiên nhẫn rèn luyện, kết nối sâu sắc với đất mẹ thiên nhiên và sự ấp ủ các dự án đầy tiềm năng phát triển.',
    meaningReversed: 'Trạng thái ngược thể hiện sự lười biếng thụ động, chậm trễ không chịu thực thi ý tưởng hoặc sự xa rời các nguyên lý thực tế của đời sống.',
    imagePath: '/Thoth_Tarot/thoth-disks-11-princess_6243623226_l.jpg'
  },
  {
    id: 75,
    slug: 'prince-of-pentacles',
    nameEn: 'Prince of Disks',
    nameVi: 'Hoàng Tử Đĩa',
    arcana: 'minor',
    suit: 'pentacles',
    number: '12',
    keywordsVi: ['thực tế vững chãi', 'chăm chỉ bền bỉ', 'phương pháp khoa học', 'chậm mà chắc'],
    meaningUpright: 'Hoàng Tử Đĩa lái chiếc xe kiên cố được kéo bởi chú bò vàng vững chãi. Anh đại diện cho tinh thần thực tế cao độ, làm việc chăm chỉ bền bỉ theo phương pháp khoa học, đề cao triết lý "chậm mà chắc" để đạt mục tiêu.',
    meaningReversed: 'Trạng thái ngược cảnh báo thói cứng đầu bướng bỉnh vô lý, sự lười biếng thụ động trì trệ hoặc xu hướng quá tham lam tiền bạc vật chất.',
    imagePath: '/Thoth_Tarot/thoth-disks-12-prince_6243109515_l.jpg'
  },
  {
    id: 76,
    slug: 'queen-of-pentacles',
    nameEn: 'Queen of Disks',
    nameVi: 'Nữ Hoàng Đĩa',
    arcana: 'minor',
    suit: 'pentacles',
    number: '13',
    keywordsVi: ['người mẹ đất', 'nuôi dưỡng trù phú', 'kinh nghiệm thực tế', 'sự yên bình'],
    meaningUpright: 'Nữ Hoàng Đĩa ngồi giữa rừng cây xum xuê bên cạnh chú dê sừng lớn thiêng liêng. Nàng là người mẹ đất bao dung nuôi dưỡng vạn vật trù phú, sở hữu kinh nghiệm quản lý tài chính xuất sắc và mang lại sự yên bình.',
    meaningReversed: 'Trạng thái ngược chỉ ra sự hoang mang lo sợ mất an toàn vật chất dẫn đến keo kiệt bủn xỉn, hoặc thói quen bao bọc nuông chiều quá mức có hại.',
    imagePath: '/Thoth_Tarot/thoth-disks-13-queen_6243112753_l.jpg'
  },
  {
    id: 77,
    slug: 'knight-of-pentacles',
    nameEn: 'Knight of Disks',
    nameVi: 'Hiệp Sĩ Đĩa',
    arcana: 'minor',
    suit: 'pentacles',
    number: '14',
    keywordsVi: ['người gieo trồng kiên nhẫn', 'thu hoạch vững vàng', 'kinh nghiệm lâu năm', 'sự bền bỉ'],
    meaningUpright: 'Hiệp Sĩ Đĩa (tương đương King of Pentacles ở RWS) cưỡi chú ngựa chiến vững chãi giám sát cánh đồng lúa chín vàng. Ông đại diện cho sự kiên nhẫn gieo trồng lâu năm mang lại vụ mùa thu hoạch cực kỳ thành công vững vàng.',
    meaningReversed: 'Trạng thái ngược cảnh báo sự sa lầy vào tư duy vật chất thực dụng thái quá, thói độc đoán bảo thủ cản trở sự đổi mới sáng tạo.',
    imagePath: '/Thoth_Tarot/thoth-disks-14-knight_6243633252_l.jpg'
  }
];

export function getCardById(id: number): TarotCard | undefined {
  return thothCards.find((card) => card.id === id);
}

export function getCardBySlug(slug: string): TarotCard | undefined {
  return thothCards.find((card) => card.slug === slug);
}
